{
  flake.nixosModules.desktop-stumpwm =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      cfg = config.desktop.stumpwm;
      user = config.user;

      # Same palette as the sway and waybar modules.
      c = {
        bg = "#16161D";
        fg = "#EFEFF4";
        muted = "#9999AA";
        accent = "#F97316";
        unfocused = "#373746";
      };

      interface = "wlp9s0";

      fontDir = "/run/current-system/sw/share/X11/fonts";
      fonts = [
        "-*-departure mono-*-r-*--16-*-*-*-*-*-iso10646-1"
        "-*-terminus-medium-r-normal--16-*-*-*-*-*-iso10646-1"
      ];

      brightnessctl = lib.getExe pkgs.brightnessctl;
      i3lock = lib.getExe' pkgs.i3lock "i3lock";
      maim = lib.getExe' pkgs.maim "maim";
      pactl = lib.getExe' pkgs.pulseaudio "pactl";
      xrdb = lib.getExe' pkgs.xrdb "xrdb";
      xset = lib.getExe' pkgs.xset "xset";
      xsetroot = lib.getExe' pkgs.xsetroot "xsetroot";
      xssLock = lib.getExe' pkgs.xss-lock "xss-lock";

      volumeCommand = "${pactl} get-sink-mute @DEFAULT_SINK@ | grep -q yes && echo MUTE || ${pactl} get-sink-volume @DEFAULT_SINK@ | head -1 | grep -oE '[0-9]+%' | head -1 | tr -d '%'";

      lispString = s: ''"${lib.escape [ "\\" "\"" ] s}"'';

      settingsLisp = ''
        ;;;; Generated by NixOS -- do not edit.
        ;;;; See modules/desktop/stumpwm/default.nix.

        (in-package :stumpwm)

        (defparameter *rc-bg* ${lispString c.bg})
        (defparameter *rc-fg* ${lispString c.fg})
        (defparameter *rc-muted-color* ${lispString c.muted})
        (defparameter *rc-accent-color* ${lispString c.accent})
        (defparameter *rc-unfocused-color* ${lispString c.unfocused})

        (defparameter *rc-fonts*
          (list ${lib.concatMapStringsSep "\n        " lispString fonts}))

        (defparameter *rc-contrib-dir* ${lispString "${pkgs.stumpwm-contrib}"})
        (defparameter *rc-interface* ${lispString interface})
        (defparameter *rc-terminal* ${lispString "alacritty"})
        (defparameter *rc-volume-command* ${lispString volumeCommand})
        (defparameter *rc-pactl* ${lispString pactl})
        (defparameter *rc-brightnessctl* ${lispString brightnessctl})
        (defparameter *rc-maim* ${lispString maim})
      '';
    in
    {
      options.desktop.stumpwm.enable = lib.mkEnableOption "StumpWM";

      config = lib.mkIf cfg.enable {
        core.fonts.enable = true;
        core.home-manager.enable = true;
        applications.alacritty.enable = true;

        services.xserver = {
          enable = true;
          fontPath = lib.mkDefault fontDir;
          windowManager.stumpwm.enable = true;

          displayManager.sessionCommands = ''
            if [ -n "$DISPLAY" ]; then
              # This head reports 139 DPI, so winit and Xft scale X clients by
              # ~1.42 while sway renders them at 1. Pin 96 to keep one look.
              printf 'Xft.dpi: 96\n' | ${xrdb} -merge -
              ${xsetroot} -solid '${c.bg}' -cursor_name left_ptr
              ${xset} s 1800 1800
              ${xset} dpms 0 0 2400
              ${xssLock} --transfer-sleep-lock -- ${i3lock} -n -c 16161d &
            fi
          '';
        };

        security.pam.services.i3lock = { };
        services.gnome.gnome-keyring.enable = true;

        xdg.portal = {
          enable = true;
          extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
        };

        environment.systemPackages = [
          pkgs.brightnessctl
          pkgs.i3lock
          pkgs.maim
          pkgs.xclip
          pkgs.xrdb
          pkgs.xset
          pkgs.xsetroot
          pkgs.xss-lock
        ];

        home-manager.users.${user.name}.home.file = {
          ".stumpwm.d/init.lisp".source = ./configurations/init.lisp;
          ".stumpwm.d/settings.lisp".text = settingsLisp;
        };
      };
    };
}
