local builtin = require("telescope.builtin")
local themes = require("telescope.themes")
local wk = require("which-key")
wk.setup({})
wk.add({{"<leader>s", {group = "[S]earch"}}, {"<leader>p", {group = "[P]roject"}}, {"<localleader>c", {group = "[C]onjure"}}})
vim.keymap.set("n", "<leader>pv", "<CMD>Oil<CR>", {desc = "[P]roject [V]iew"})
vim.keymap.set("n", "<leader>pt", "<CMD>NvimTreeToggle<CR>", {desc = "[P]roject [T]ree"})
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv", {desc = "Selection Up"})
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv", {desc = "Selection Down"})
vim.keymap.set("n", "J", "mzJ`z", {})
vim.keymap.set("n", "<C-d>", "<C-d>zz", {})
vim.keymap.set("n", "<C-u>", "<C-u>zz", {})
vim.keymap.set("n", "n", "nzzzv", {})
vim.keymap.set("n", "N", "Nzzzv", {})
vim.keymap.set("x", "<leader>p", "\"_dP", {})
vim.keymap.set({"n", "v"}, "<leader>y", "\"+y", {desc = "[Y]ank to clipboard"})
vim.keymap.set("n", "<leader>Y", "\"+Y", {desc = "[Y]ank line to clipboard"})
vim.keymap.set({"n", "v"}, "<leader>d", "\"_d", {})
vim.keymap.set("i", "<C-c>", "<Esc>", {})
vim.keymap.set("n", "Q", "<nop>", {})
vim.keymap.set("n", "<C-f>", "<cmd>silent !tmux neww tmux-sessionizer<CR>", {})
vim.keymap.set("n", "<C-k>", "<cmd>cnext<CR>zz", {})
vim.keymap.set("n", "<C-j>", "<cmd>cprev<CR>zz", {})
vim.keymap.set("n", "<leader>k", "<cmd>lnext<CR>zz", {desc = "Next error"})
vim.keymap.set("n", "<leader>j", "<cmd>lprev<CR>zz", {desc = "Previous error"})
vim.keymap.set("n", "<C-s>", ":%s/\\<<C-r><C-w>\\>/<C-r><C-w>/gI<Left><Left><Left>", {})
vim.keymap.set("n", "<leader>x", "<cmd>!chmod +x %<CR>", {desc = "Make a file executable", silent = true})
vim.keymap.set("n", "<leader>sh", builtin.help_tags, {desc = "[S]earch [H]elp"})
vim.keymap.set("n", "<leader>sk", builtin.keymaps, {desc = "[S]earch [K]eymaps"})
vim.keymap.set("n", "<leader>sf", builtin.find_files, {desc = "[S]earch [F]iles"})
vim.keymap.set("n", "<leader>ss", builtin.builtin, {desc = "[S]earch [S]elect Telescope"})
vim.keymap.set("n", "<leader>sw", builtin.grep_string, {desc = "[S]earch current [W]ord"})
vim.keymap.set("n", "<leader>sg", builtin.live_grep, {desc = "[S]earch by [G]rep"})
vim.keymap.set("n", "<leader>sd", builtin.diagnostics, {desc = "[S]earch [D]iagnostics"})
vim.keymap.set("n", "<leader>sr", builtin.resume, {desc = "[S]earch [R]esume"})
vim.keymap.set("n", "<leader>s.", builtin.oldfiles, {desc = "[S]earch Recent Files ('.' for repeat)"})
vim.keymap.set("n", "<leader><leader>", builtin.buffers, {desc = "[ ] Find existing buffers"})
local function _1_()
  return builtin.current_buffer_fuzzy_find(themes.get_dropdown({winblend = 10, previewer = false}))
end
vim.keymap.set("n", "<leader>/", _1_, {desc = "[/] Fuzzily search in current buffer"})
local function _2_()
  return builtin.live_grep({grep_open_files = true, prompt_title = "Live Grep in Open Files"})
end
vim.keymap.set("n", "<leader>s/", _2_, {desc = "[S]earch [/] in Open Files"})
local function _3_()
  return builtin.find_files({cwd = vim.fn.stdpath("config")})
end
vim.keymap.set("n", "<leader>sn", _3_, {desc = "[S]earch [N]eovim files"})
local function _4_()
  return vim.cmd("UndotreeToggle")
end
return vim.keymap.set("n", "<leader>u", _4_, {desc = "[U]ndo tree"})
