;;; borealis-nebula-theme.el --- Borealis lights over a deep space canvas  -*- lexical-binding:t -*-

;;; Commentary:
;; The Borealis theme moved out of the atmosphere

;;; Code:

;;;###theme-autoload
(deftheme borealis-nebula
  "Borealis lights over a deep space canvas."
  :background-mode 'dark
  :kind 'color-scheme
  :family 'borealis)

(custom-theme-set-faces
 'borealis-nebula

 '(default ((t (:background "#0d1117" :foreground "#e6edf3"))))
 '(cursor ((t (:background "#2f81f7"))))
 '(region ((t (:background "#30363d"))))
 '(highlight ((t (:background "#1c2128"))))
 '(hl-line ((t (:background "#161b22"))))
 '(fringe ((t (:background unspecified))))
 '(vertical-border ((t (:foreground "#484f58" :background "#0d1117"))))
 '(minibuffer-prompt ((t (:foreground "#79c0ff" :weight bold))))
 '(isearch ((t (:background "#1f6feb" :foreground "#ffffff"))))
 '(lazy-highlight ((t (:background "#30363d"))))
 '(link ((t (:foreground "#79c0ff" :underline t))))
 '(link-visited ((t (:foreground "#d2a8ff" :underline t))))
 '(button ((t (:inherit link))))
 '(header-line ((t (:background "#161b22" :foreground "#e6edf3"))))
 '(tooltip ((t (:background "#161b22" :foreground "#e6edf3"))))
 '(secondary-selection ((t (:background "#1c2128"))))

 '(font-lock-builtin-face ((t (:foreground "#d2a8ff"))))
 '(font-lock-comment-face ((t (:foreground "#8b949e"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#8b949e"))))
 '(font-lock-constant-face ((t (:foreground "#bc8cff"))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground "#b1bac4"))))
 '(font-lock-function-name-face ((t (:foreground "#79c0ff"))))
 '(font-lock-keyword-face ((t (:foreground "#56d364" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#bc8cff" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#ff7b72" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#f2cc60"))))
 '(font-lock-type-face ((t (:foreground "#56d4dd"))))
 '(font-lock-variable-name-face ((t (:foreground unspecified))))
 '(font-lock-warning-face ((t (:foreground "#f2cc60" :weight bold))))

 '(font-lock-operator-face ((t (:foreground "#e6edf3"))))
 '(font-lock-punctuation-face ((t (:foreground "#e6edf3"))))
 '(font-lock-bracket-face ((t (:foreground "#e6edf3"))))
 '(font-lock-delimiter-face ((t (:foreground "#e6edf3"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#ff7b72"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#ff7b72"))))

 '(mode-line ((t (:background "#010409" :foreground "#e6edf3"))))
 '(mode-line-inactive ((t (:background "#161b22" :foreground "#8b949e"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#79c0ff"))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "#484f58")))))

 '(line-number ((t (:foreground "#484f58" :background unspecified))))
 '(line-number-current-line ((t (:foreground "#e6edf3" :background unspecified :weight bold))))

 '(show-paren-match ((t (:background "#1f6feb" :foreground "#ffffff" :weight bold))))
 '(show-paren-mismatch ((t (:background "#ff7b72" :foreground "#0d1117"))))

 '(match ((t (:background "#30363d"))))
 '(query-replace ((t (:inherit isearch))))

 '(diff-added ((t (:background "#152a1f" :foreground "#56d364"))))
 '(diff-removed ((t (:background "#301b1e" :foreground "#ff7b72"))))
 '(diff-changed ((t (:background "#2b2519" :foreground "#f2cc60"))))
 '(diff-header ((t (:background "#161b22" :weight bold))))
 '(diff-file-header ((t (:background "#161b22" :foreground "#79c0ff" :weight bold))))

 '(compilation-error ((t (:foreground "#ff7b72" :weight bold))))
 '(compilation-warning ((t (:foreground "#f2cc60" :weight bold))))
 '(compilation-info ((t (:foreground "#56d364"))))
 '(compilation-line-number ((t (:foreground "#79c0ff"))))

 '(org-level-1 ((t (:foreground "#56d364" :weight bold))))
 '(org-level-2 ((t (:foreground "#56d364" :weight bold))))
 '(org-level-3 ((t (:foreground "#56d364" :weight bold))))
 '(org-level-4 ((t (:foreground "#56d364"))))
 '(org-level-5 ((t (:foreground "#56d364"))))
 '(org-level-6 ((t (:foreground "#56d364"))))
 '(org-level-7 ((t (:foreground "#56d364"))))
 '(org-level-8 ((t (:foreground "#56d364"))))
 '(org-todo ((t (:foreground "#ff7b72" :weight bold))))
 '(org-done ((t (:foreground "#56d364" :weight bold))))
 '(org-headline-done ((t (:strike-through t))))
 '(org-date ((t (:foreground "#56d4dd" :underline t))))
 '(org-link ((t (:foreground "#79c0ff" :underline t))))
 '(org-block ((t (:background "#1c2128"))))
 '(org-block-begin-line ((t (:foreground "#8b949e" :background "#1c2128"))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-code ((t (:foreground "#d2a8ff"))))
 '(org-verbatim ((t (:foreground "#f2cc60"))))

 '(outline-1 ((t (:foreground "#56d364" :weight bold))))
 '(outline-2 ((t (:foreground "#79c0ff" :weight bold))))
 '(outline-3 ((t (:foreground "#56d4dd" :weight bold))))
 '(outline-4 ((t (:foreground "#f2cc60" :weight bold))))
 '(outline-5 ((t (:foreground "#d2a8ff" :weight bold))))
 '(outline-6 ((t (:foreground "#bc8cff" :weight bold))))
 '(outline-7 ((t (:foreground "#ff7b72" :weight bold))))
 '(outline-8 ((t (:foreground "#ffa657" :weight bold))))

 '(dired-directory ((t (:foreground "#79c0ff" :weight bold))))
 '(dired-symlink ((t (:foreground "#56d4dd"))))
 '(dired-header ((t (:foreground "#e6edf3" :weight bold))))

 '(eshell-prompt ((t (:foreground "#79c0ff" :weight bold))))
 '(eshell-ls-directory ((t (:foreground "#79c0ff" :weight bold))))
 '(eshell-ls-executable ((t (:foreground "#56d364"))))
 '(eshell-ls-symlink ((t (:foreground "#56d4dd"))))

 '(company-tooltip ((t (:background "#161b22" :foreground "#e6edf3"))))
 '(company-tooltip-selection ((t (:background "#30363d"))))
 '(company-tooltip-common ((t (:foreground "#79c0ff"))))
 '(company-scrollbar-fg ((t (:background "#484f58"))))
 '(company-scrollbar-bg ((t (:background "#1c2128"))))

 '(corfu-default ((t (:background "#161b22" :foreground "#e6edf3"))))
 '(corfu-current ((t (:background "#30363d" :foreground "#e6edf3"))))
 '(corfu-bar ((t (:background "#484f58"))))
 '(corfu-border ((t (:background "#30363d"))))
 '(corfu-annotations ((t (:foreground "#8b949e"))))
 '(corfu-deprecated ((t (:foreground "#484f58" :strike-through t))))
 '(corfu-echo ((t (:foreground "#8b949e"))))
 '(corfu-popupinfo ((t (:background "#161b22" :foreground "#e6edf3"))))

 '(flycheck-error ((t (:underline (:style wave :color "#ff7b72")))))
 '(flycheck-warning ((t (:underline (:style wave :color "#f2cc60")))))
 '(flycheck-info ((t (:underline (:style wave :color "#79c0ff")))))

 '(git-gutter:added ((t (:foreground "#56d364"))))
 '(git-gutter:deleted ((t (:foreground "#ff7b72"))))
 '(git-gutter:modified ((t (:foreground "#ffa657"))))

 '(magit-branch-current ((t (:foreground "#79c0ff" :weight bold))))
 '(magit-branch-local ((t (:foreground "#56d4dd"))))
 '(magit-branch-remote ((t (:foreground "#56d364"))))
 '(magit-branch-upstream ((t (:foreground "#56d364"))))
 '(magit-tag ((t (:foreground "#f2cc60"))))
 '(magit-hash ((t (:foreground "#8b949e"))))
 '(magit-section-heading ((t (:foreground "#79c0ff" :weight bold))))
 '(magit-section-highlight ((t (:background "#1c2128"))))
 '(magit-section-heading-selection ((t (:background "#30363d" :foreground "#ff7b72"))))
 '(magit-diff-file-heading ((t (:background "#161b22" :foreground "#e6edf3"))))
 '(magit-diff-file-heading-highlight ((t (:background "#1c2128" :foreground "#e6edf3"))))
 '(magit-diff-hunk-heading ((t (:background "#1c2128" :foreground "#8b949e"))))
 '(magit-diff-hunk-heading-highlight ((t (:background "#30363d" :foreground "#e6edf3"))))
 '(magit-diff-context ((t (:foreground "#e6edf3"))))
 '(magit-diff-context-highlight ((t (:background "#161b22" :foreground "#e6edf3"))))
 '(magit-diff-added ((t (:background "#152a1f" :foreground "#56d364"))))
 '(magit-diff-added-highlight ((t (:background "#21542e" :foreground "#56d364"))))
 '(magit-diff-removed ((t (:background "#301b1e" :foreground "#ff7b72"))))
 '(magit-diff-removed-highlight ((t (:background "#6b2b2b" :foreground "#ffa198"))))
 '(magit-diffstat-added ((t (:foreground "#56d364"))))
 '(magit-diffstat-removed ((t (:foreground "#ff7b72"))))
 '(magit-log-author ((t (:foreground "#56d4dd"))))
 '(magit-log-date ((t (:foreground "#8b949e"))))
 '(magit-log-graph ((t (:foreground "#484f58"))))
 '(magit-process-ok ((t (:foreground "#56d364" :weight bold))))
 '(magit-process-ng ((t (:foreground "#ff7b72" :weight bold))))

 '(vertico-current ((t (:background "#30363d" :extend t))))
 '(vertico-group-title ((t (:background "#1c2128" :foreground "#8b949e" :weight bold))))
 '(vertico-group-separator ((t (:background "#1c2128" :foreground "#484f58" :strike-through t))))
 '(vertico-multiline ((t (:foreground "#8b949e"))))
 '(vertico-quick1 ((t (:background "#161b22" :foreground "#79c0ff" :weight bold))))
 '(vertico-quick2 ((t (:background "#161b22" :foreground "#56d364" :weight bold))))

 '(orderless-match-face-0 ((t (:foreground "#79c0ff" :weight bold))))
 '(orderless-match-face-1 ((t (:foreground "#56d364" :weight bold))))
 '(orderless-match-face-2 ((t (:foreground "#f2cc60" :weight bold))))
 '(orderless-match-face-3 ((t (:foreground "#d2a8ff" :weight bold))))

 '(marginalia-documentation ((t (:foreground "#8b949e"))))
 '(marginalia-key ((t (:foreground "#56d364"))))
 '(marginalia-type ((t (:foreground "#d2a8ff"))))
 '(marginalia-char ((t (:foreground "#79c0ff"))))
 '(marginalia-lighter ((t (:foreground "#484f58"))))
 '(marginalia-on ((t (:foreground "#56d364"))))
 '(marginalia-off ((t (:foreground "#ff7b72"))))

 '(consult-file ((t (:foreground "#e6edf3"))))
 '(consult-bookmark ((t (:foreground "#79c0ff"))))
 '(consult-async-running ((t (:foreground "#79c0ff"))))
 '(consult-async-finished ((t (:foreground "#56d364"))))
 '(consult-async-failed ((t (:foreground "#ff7b72"))))
 '(consult-preview-line ((t (:background "#1c2128"))))
 '(consult-preview-match ((t (:background "#30363d"))))

 '(ivy-current-match ((t (:background "#1f6feb" :foreground "#ffffff"))))
 '(ivy-minibuffer-match-face-1 ((t (:background "#1c2128"))))
 '(helm-selection ((t (:background "#30363d"))))
 '(helm-match ((t (:foreground "#79c0ff" :weight bold))))

 '(term-color-black ((t (:foreground "#484f58" :background "#484f58"))))
 '(term-color-red ((t (:foreground "#ff7b72" :background "#ff7b72"))))
 '(term-color-green ((t (:foreground "#3fb950" :background "#3fb950"))))
 '(term-color-yellow ((t (:foreground "#e3b341" :background "#e3b341"))))
 '(term-color-blue ((t (:foreground "#58a6ff" :background "#58a6ff"))))
 '(term-color-magenta ((t (:foreground "#bc8cff" :background "#bc8cff"))))
 '(term-color-cyan ((t (:foreground "#39c5cf" :background "#39c5cf"))))
 '(term-color-white ((t (:foreground "#b1bac4" :background "#b1bac4"))))
 '(term-color-bright-black ((t (:foreground "#6e7681" :background "#6e7681"))))
 '(term-color-bright-red ((t (:foreground "#ffa198" :background "#ffa198"))))
 '(term-color-bright-green ((t (:foreground "#56d364" :background "#56d364"))))
 '(term-color-bright-yellow ((t (:foreground "#f2cc60" :background "#f2cc60"))))
 '(term-color-bright-blue ((t (:foreground "#79c0ff" :background "#79c0ff"))))
 '(term-color-bright-magenta ((t (:foreground "#d2a8ff" :background "#d2a8ff"))))
 '(term-color-bright-cyan ((t (:foreground "#56d4dd" :background "#56d4dd"))))
 '(term-color-bright-white ((t (:foreground "#ffffff" :background "#ffffff"))))

 '(rainbow-delimiters-depth-1-face ((t (:foreground "#ff7b72"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#ffa657"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#f2cc60"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#56d364"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#56d4dd"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#79c0ff"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#d2a8ff"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#bc8cff"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#39c5cf"))))

 '(lsp-face-highlight-textual ((t (:background "#30363d"))))
 '(lsp-face-highlight-read ((t (:background "#30363d"))))
 '(lsp-face-highlight-write ((t (:background "#30363d" :underline t))))
 '(lsp-ui-doc-background ((t (:background "#161b22"))))
 '(lsp-ui-peek-selection ((t (:background "#30363d"))))
 '(lsp-ui-sideline-code-action ((t (:foreground "#f2cc60"))))
 '(lsp-face-semhl-operator ((t (:foreground "#e6edf3"))))
 '(lsp-face-semhl-constant ((t (:foreground "#bc8cff" :weight bold))))
 '(lsp-face-semhl-namespace ((t (:foreground "#56d4dd"))))
 '(lsp-inlay-hint-face ((t (:foreground "#484f58"))))

 '(which-key-key-face ((t (:foreground "#56d364"))))
 '(which-key-separator-face ((t (:foreground "#484f58"))))
 '(which-key-command-description-face ((t (:foreground "#e6edf3"))))

 '(web-mode-html-tag-face ((t (:foreground "#d2a8ff"))))
 '(web-mode-html-attr-name-face ((t (:foreground "#ffa657"))))
 '(web-mode-html-attr-value-face ((t (:foreground "#f2cc60"))))
 '(web-mode-css-selector-face ((t (:foreground "#79c0ff"))))
 '(web-mode-css-property-name-face ((t (:foreground "#56d4dd"))))

 '(js2-function-param ((t (:foreground "#e6edf3"))))
 '(js2-function-call ((t (:foreground "#79c0ff"))))
 '(js2-object-property ((t (:foreground "#e6edf3"))))
 '(js2-jsdoc-tag ((t (:foreground "#b1bac4"))))
 '(js2-external-variable ((t (:foreground "#e6edf3"))))

 '(markdown-header-face-1 ((t (:foreground "#56d364" :weight bold))))
 '(markdown-header-face-2 ((t (:foreground "#56d364" :weight bold))))
 '(markdown-header-face-3 ((t (:foreground "#56d364" :weight bold))))
 '(markdown-header-face-4 ((t (:foreground "#56d364"))))
 '(markdown-bold-face ((t (:foreground "#ff7b72" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#ff7b72" :slant italic))))
 '(markdown-link-face ((t (:foreground "#79c0ff"))))
 '(markdown-url-face ((t (:foreground "#ffa657"))))
 '(markdown-code-face ((t (:background "#1c2128"))))
 '(markdown-blockquote-face ((t (:foreground "#79c0ff"))))

 '(treemacs-root-face ((t (:inherit font-lock-string-face :weight bold :height 1.2))))
 '(treemacs-directory-face ((t (:foreground "#e6edf3"))))
 '(treemacs-file-face ((t (:foreground "#e6edf3"))))
 '(treemacs-tags-face ((t (:foreground "#79c0ff"))))
 '(treemacs-fringe-indicator-face ((t (:foreground "#79c0ff"))))
 '(treemacs-git-added-face ((t (:foreground "#56d364"))))
 '(treemacs-git-modified-face ((t (:foreground "#d2a8ff"))))
 '(treemacs-git-conflict-face ((t (:foreground "#ff7b72"))))
 '(treemacs-git-untracked-face ((t (:inherit font-lock-doc-face))))
 '(treemacs-on-success-pulse-face ((t (:background "#56d364" :foreground "#010409" :extend t))))
 '(treemacs-on-failure-pulse-face ((t (:background "#ff7b72" :foreground "#010409" :extend t))))

 '(window-divider ((t (:inherit vertical-border))))
 '(window-divider-first-pixel ((t (:inherit window-divider))))
 '(window-divider-last-pixel ((t (:inherit window-divider))))

 ;; elfeed
 '(elfeed-log-debug-level-face ((t (:foreground "#8b949e"))))
 '(elfeed-log-error-level-face ((t (:inherit error))))
 '(elfeed-log-info-level-face ((t (:inherit success))))
 '(elfeed-log-warn-level-face ((t (:inherit warning))))
 '(elfeed-search-date-face ((t (:foreground "#bc8cff"))))
 '(elfeed-search-feed-face ((t (:foreground "#79c0ff"))))
 '(elfeed-search-filter-face ((t (:foreground "#bc8cff"))))
 '(elfeed-search-last-modified-face ((t (:foreground "#8b949e"))))
 '(elfeed-search-tag-face ((t (:foreground "#8b949e"))))
 '(elfeed-search-title-face ((t (:foreground "#8b949e"))))
 '(elfeed-search-unread-count-face ((t (:foreground "#f2cc60"))))
 '(elfeed-search-unread-title-face ((t (:foreground "#e6edf3" :weight bold))))

 ;; local preferences
 '(font-lock-variable-use-face ((t (:foreground unspecified))))
 '(lsp-face-semhl-property ((t (:foreground unspecified))))
 '(lsp-face-semhl-member ((t (:foreground unspecified))))
 '(lsp-face-semhl-variable ((t (:foreground unspecified))))
 '(lsp-face-semhl-parameter ((t (:foreground unspecified))))
 '(lsp-face-semhl-macro ((t (:foreground "#ff7b72"))))
 '(lsp-rust-analyzer-mutable-modifier-face ((t (:underline nil))))

 '(error ((t (:foreground "#ff7b72" :weight bold))))
 '(warning ((t (:foreground "#f2cc60" :weight bold))))
 '(success ((t (:foreground "#56d364" :weight bold)))))

(provide-theme 'borealis-nebula)

;;; borealis-nebula-theme.el ends here
