;;;; photopic-theme.el --- A near-monochrome light theme  -*- lexical-binding:t -*-

;;; Commentary:

;; A near-monochrome light theme.

;;; Code:

;;;###theme-autoload
(deftheme photopic
  "A near-monochrome light theme."
  :background-mode 'light
  :kind 'color-scheme
  :family 'photopic)

(custom-theme-set-faces
 'photopic
 '(default                            ((t (:background "#ffffff" :foreground "#000000"))))
 '(cursor                             ((t (:background "#000000"))))
 '(region                             ((t (:background "#f0f0f0" :extend t))))
 '(highlight                          ((t (:background "#f0f0f0"))))
 '(hl-line                            ((t (:background "#f7f7f7" :extend t))))
 '(fringe                             ((t (:foreground "#999999" :background unspecified))))
 '(vertical-border                    ((t (:foreground "#e6e6e6" :background "#ffffff"))))
 '(minibuffer-prompt                  ((t (:foreground "#000000"))))
 '(isearch                            ((t (:background "#e6e6e6" :foreground "#000000" :weight bold))))
 '(lazy-highlight                     ((t (:background "#f0f0f0"))))
 '(link                               ((t (:foreground "#221199" :underline t))))
 '(link-visited                       ((t (:foreground "#999999" :underline t))))
 '(button                             ((t (:inherit link))))
 '(header-line                        ((t (:background "#ffffff" :foreground "#000000"))))
 '(tooltip                            ((t (:background "#f0f0f0" :foreground "#000000"))))
 '(secondary-selection                ((t (:background "#f0f0f0" :foreground "#999999"))))
 '(shadow                             ((t (:foreground "#999999"))))
 '(trailing-whitespace                ((t (:background "#f0f0f0"))))
 '(escape-glyph                       ((t (:foreground "#00a896"))))
 '(homoglyph                          ((t (:foreground "#00a896"))))

 '(font-lock-builtin-face             ((t (:foreground "#221199"))))
 '(font-lock-comment-face             ((t (:foreground "#999999"))))
 '(font-lock-comment-delimiter-face   ((t (:inherit font-lock-comment-face))))
 '(font-lock-constant-face            ((t (:foreground "#221199"))))
 '(font-lock-doc-face                 ((t (:inherit font-lock-comment-face))))
 '(font-lock-function-name-face       ((t (:foreground "#000000"))))
 '(font-lock-keyword-face             ((t (:foreground "#000000" :weight bold))))
 '(font-lock-negation-char-face       ((t (:foreground "#ff6347"))))
 '(font-lock-preprocessor-face        ((t (:foreground "#221199"))))
 '(font-lock-string-face              ((t (:foreground "#00a896"))))
 '(font-lock-type-face                ((t (:foreground "#221199"))))
 '(font-lock-variable-name-face       ((t (:foreground unspecified))))
 '(font-lock-warning-face             ((t (:foreground "#00a896"))))

 '(font-lock-operator-face            ((t (:foreground "#000000"))))
 '(font-lock-punctuation-face         ((t (:foreground "#999999"))))
 '(font-lock-bracket-face             ((t (:inherit font-lock-punctuation-face))))
 '(font-lock-delimiter-face           ((t (:inherit font-lock-punctuation-face))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#00a896"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#00a896"))))

 '(mode-line                          ((t (:background "#ffffff" :foreground "#aaaaaa" :box nil :overline "#e6e6e6"))))
 '(mode-line-inactive                 ((t (:background "#ffffff" :foreground "#e6e6e6" :box nil :overline "#f0f0f0"))))
 '(mode-line-buffer-id                ((t (:foreground "#000000"))))
 '(mode-line-emphasis                 ((t (:foreground "#000000"))))
 '(mode-line-highlight                ((t (:foreground "#000000"))))

 '(line-number                        ((t (:foreground "#999999" :background unspecified))))
 '(line-number-current-line           ((t (:foreground "#000000" :background unspecified))))

 '(show-paren-match                   ((t (:background "#cceeea" :foreground "#000000" :weight bold))))
 '(show-paren-mismatch                ((t (:background "#ff6347" :foreground "#ffffff"))))

 '(match                              ((t (:background "#f0f0f0"))))
 '(query-replace                      ((t (:inherit isearch))))

 '(diff-added                         ((t (:background "#eaf8f6" :foreground "#000000"))))
 '(diff-removed                       ((t (:background "#ffefec" :foreground "#000000"))))
 '(diff-changed                       ((t (:background "#f0f0f0" :foreground "#000000"))))
 '(diff-header                        ((t (:background "#f0f0f0" :foreground "#000000"))))
 '(diff-file-header                   ((t (:background "#f0f0f0" :foreground "#221199" :weight bold))))

 '(compilation-error                  ((t (:foreground "#ff6347" :weight bold))))
 '(compilation-warning                ((t (:foreground "#00a896" :weight bold))))
 '(compilation-info                   ((t (:foreground "#221199"))))
 '(compilation-line-number            ((t (:foreground "#999999"))))

 '(org-level-1                        ((t (:foreground "#000000" :weight bold))))
 '(org-level-2                        ((t (:foreground "#000000" :weight bold))))
 '(org-level-3                        ((t (:foreground "#000000" :weight bold))))
 '(org-level-4                        ((t (:foreground "#000000" :weight bold))))
 '(org-level-5                        ((t (:foreground "#000000" :weight bold))))
 '(org-level-6                        ((t (:foreground "#000000" :weight bold))))
 '(org-level-7                        ((t (:foreground "#000000" :weight bold))))
 '(org-level-8                        ((t (:foreground "#000000" :weight bold))))
 '(org-todo                           ((t (:foreground "#ff6347" :weight bold))))
 '(org-done                           ((t (:foreground "#999999" :weight bold))))
 '(org-headline-done                  ((t (:foreground "#999999"))))
 '(org-date                           ((t (:foreground "#999999" :underline t))))
 '(org-link                           ((t (:foreground "#00a896" :underline t))))
 '(org-block                          ((t (:background "#f7f7f7"))))
 '(org-block-begin-line               ((t (:foreground "#aaaaaa" :background "#f0f0f0"))))
 '(org-block-end-line                 ((t (:inherit org-block-begin-line))))
 '(org-code                           ((t (:foreground "#000000" :background "#f0f0f0"))))
 '(org-verbatim                       ((t (:foreground "#221199"))))
 '(org-document-title                 ((t (:foreground "#000000" :weight bold))))
 '(org-document-info                  ((t (:foreground "#999999"))))
 '(org-meta-line                      ((t (:foreground "#aaaaaa"))))
 '(org-drawer                         ((t (:foreground "#aaaaaa"))))
 '(org-special-keyword                ((t (:foreground "#aaaaaa"))))
 '(org-table                          ((t (:foreground "#000000"))))
 '(org-tag                            ((t (:foreground "#999999"))))
 '(org-ellipsis                       ((t (:foreground "#aaaaaa" :underline nil))))

 '(outline-1                          ((t (:foreground "#000000" :weight bold))))
 '(outline-2                          ((t (:foreground "#000000" :weight bold))))
 '(outline-3                          ((t (:foreground "#000000" :weight bold))))
 '(outline-4                          ((t (:foreground "#000000" :weight bold))))
 '(outline-5                          ((t (:foreground "#000000" :weight bold))))
 '(outline-6                          ((t (:foreground "#000000" :weight bold))))
 '(outline-7                          ((t (:foreground "#000000" :weight bold))))
 '(outline-8                          ((t (:foreground "#000000" :weight bold))))

 '(dired-directory                    ((t (:foreground "#221199"))))
 '(dired-symlink                      ((t (:foreground "#00a896"))))
 '(dired-header                       ((t (:foreground "#000000" :weight bold))))
 '(dired-ignored                      ((t (:foreground "#aaaaaa"))))

 '(eshell-prompt                      ((t (:foreground "#000000" :weight bold))))
 '(eshell-ls-directory                ((t (:foreground "#221199"))))
 '(eshell-ls-executable               ((t (:foreground "#00a896"))))
 '(eshell-ls-symlink                  ((t (:foreground "#00a896"))))

 '(corfu-default                      ((t (:background "#f0f0f0" :foreground "#000000"))))
 '(corfu-current                      ((t (:background "#e6e6e6" :foreground "#000000"))))
 '(corfu-bar                          ((t (:background "#aaaaaa"))))
 '(corfu-border                       ((t (:background "#e6e6e6"))))
 '(corfu-annotations                  ((t (:foreground "#999999"))))
 '(corfu-deprecated                   ((t (:foreground "#aaaaaa" :strike-through t))))
 '(corfu-echo                         ((t (:foreground "#999999"))))
 '(corfu-popupinfo                    ((t (:background "#f0f0f0" :foreground "#000000"))))
 '(cape-keyword                       ((t (:foreground "#221199"))))

 '(company-tooltip                    ((t (:background "#f0f0f0" :foreground "#000000"))))
 '(company-tooltip-selection          ((t (:background "#e6e6e6"))))
 '(company-tooltip-common             ((t (:foreground "#221199"))))
 '(company-scrollbar-fg               ((t (:background "#aaaaaa"))))
 '(company-scrollbar-bg               ((t (:background "#f0f0f0"))))

 '(flycheck-error                     ((t (:underline (:style wave :color "#ff6347")))))
 '(flycheck-warning                   ((t (:underline (:style wave :color "#00a896")))))
 '(flycheck-info                      ((t (:underline (:style wave :color "#221199")))))

 '(flymake-error                      ((t (:underline (:style wave :color "#ff6347")))))
 '(flymake-warning                    ((t (:underline (:style wave :color "#00a896")))))
 '(flymake-note                       ((t (:underline (:style wave :color "#221199")))))

 '(git-gutter:added                   ((t (:foreground "#00a896"))))
 '(git-gutter:deleted                 ((t (:foreground "#ff6347"))))
 '(git-gutter:modified                ((t (:foreground "#221199"))))

 '(magit-branch-current               ((t (:foreground "#221199" :weight bold))))
 '(magit-branch-local                 ((t (:foreground "#221199"))))
 '(magit-branch-remote                ((t (:foreground "#00a896"))))
 '(magit-branch-upstream              ((t (:foreground "#00a896"))))
 '(magit-tag                          ((t (:foreground "#999999"))))
 '(magit-hash                         ((t (:foreground "#999999"))))
 '(magit-section-heading              ((t (:foreground "#000000" :weight bold))))
 '(magit-section-highlight            ((t (:background "#f7f7f7"))))
 '(magit-section-heading-selection    ((t (:background "#f0f0f0" :foreground "#ff6347"))))
 '(magit-diff-file-heading            ((t (:background "#ffffff" :foreground "#000000"))))
 '(magit-diff-file-heading-highlight  ((t (:background "#f0f0f0" :foreground "#000000"))))
 '(magit-diff-hunk-heading            ((t (:background "#f7f7f7" :foreground "#999999"))))
 '(magit-diff-hunk-heading-highlight  ((t (:background "#f0f0f0" :foreground "#000000"))))
 '(magit-diff-hunk-heading-selection  ((t (:background "#e6e6e6" :foreground "#ff6347"))))
 '(magit-diff-context                 ((t (:foreground "#999999"))))
 '(magit-diff-context-highlight       ((t (:background "#f7f7f7" :foreground "#000000"))))
 '(magit-diff-added                   ((t (:background "#f2fbfa" :foreground "#000000"))))
 '(magit-diff-added-highlight         ((t (:background "#eaf8f6" :foreground "#000000"))))
 '(magit-diff-removed                 ((t (:background "#fff5f3" :foreground "#000000"))))
 '(magit-diff-removed-highlight       ((t (:background "#ffefec" :foreground "#000000"))))
 '(magit-diff-lines-heading           ((t (:background "#e6e6e6" :foreground "#000000"))))
 '(magit-diff-lines-boundary          ((t (:background "#e6e6e6" :foreground "#000000"))))
 '(magit-diffstat-added               ((t (:foreground "#00a896"))))
 '(magit-diffstat-removed             ((t (:foreground "#ff6347"))))
 '(magit-log-author                   ((t (:foreground "#221199"))))
 '(magit-log-date                     ((t (:foreground "#999999"))))
 '(magit-log-graph                    ((t (:foreground "#aaaaaa"))))
 '(magit-process-ok                   ((t (:foreground "#00a896" :weight bold))))
 '(magit-process-ng                   ((t (:foreground "#ff6347" :weight bold))))
 '(magit-reflog-commit                ((t (:foreground "#00a896"))))
 '(magit-reflog-amend                 ((t (:foreground "#221199"))))
 '(magit-reflog-merge                 ((t (:foreground "#00a896"))))
 '(magit-reflog-checkout              ((t (:foreground "#221199"))))
 '(magit-reflog-reset                 ((t (:foreground "#ff6347"))))
 '(magit-reflog-rebase                ((t (:foreground "#221199"))))
 '(magit-reflog-cherry-pick           ((t (:foreground "#00a896"))))
 '(magit-reflog-remote                ((t (:foreground "#00a896"))))
 '(magit-reflog-other                 ((t (:foreground "#999999"))))
 '(magit-bisect-good                  ((t (:foreground "#00a896"))))
 '(magit-bisect-skip                  ((t (:foreground "#999999"))))
 '(magit-bisect-bad                   ((t (:foreground "#ff6347"))))
 '(magit-blame-heading                ((t (:background "#f0f0f0" :foreground "#999999"))))
 '(magit-blame-highlight              ((t (:background "#f0f0f0" :foreground "#000000"))))
 '(magit-blame-name                   ((t (:foreground "#221199"))))
 '(magit-blame-date                   ((t (:foreground "#999999"))))
 '(magit-blame-summary                ((t (:foreground "#999999"))))
 '(magit-sequence-pick                ((t (:foreground "#999999"))))
 '(magit-sequence-stop                ((t (:foreground "#00a896"))))
 '(magit-sequence-part                ((t (:foreground "#999999"))))
 '(magit-sequence-head                ((t (:foreground "#221199"))))
 '(magit-sequence-drop                ((t (:foreground "#ff6347"))))
 '(magit-sequence-done                ((t (:foreground "#999999"))))
 '(magit-sequence-onto                ((t (:foreground "#999999"))))
 '(magit-filename                     ((t (:foreground "#000000"))))
 '(magit-header-line                  ((t (:background "#ffffff" :foreground "#000000" :weight bold))))
 '(magit-header-line-log-select       ((t (:background "#ffffff" :foreground "#000000" :weight bold))))
 '(magit-mode-line-process            ((t (:foreground "#221199" :weight bold))))
 '(magit-mode-line-process-error      ((t (:foreground "#ff6347" :weight bold))))

 '(vertico-current                    ((t (:background "#f0f0f0" :extend t))))
 '(vertico-group-title                ((t (:foreground "#999999" :weight bold))))
 '(vertico-group-separator            ((t (:foreground "#e6e6e6" :strike-through t))))
 '(vertico-multiline                  ((t (:foreground "#999999"))))
 '(vertico-quick1                     ((t (:background "#f0f0f0" :foreground "#221199" :weight bold))))
 '(vertico-quick2                     ((t (:background "#f0f0f0" :foreground "#00a896" :weight bold))))

 '(orderless-match-face-0             ((t (:foreground "#221199" :weight bold))))
 '(orderless-match-face-1             ((t (:foreground "#00a896" :weight bold))))
 '(orderless-match-face-2             ((t (:foreground "#000000" :weight bold))))
 '(orderless-match-face-3             ((t (:foreground "#999999" :weight bold))))

 '(marginalia-documentation           ((t (:foreground "#999999"))))
 '(marginalia-key                     ((t (:foreground "#221199"))))
 '(marginalia-type                    ((t (:foreground "#999999"))))
 '(marginalia-char                    ((t (:foreground "#00a896"))))
 '(marginalia-lighter                 ((t (:foreground "#aaaaaa"))))
 '(marginalia-on                      ((t (:foreground "#00a896"))))
 '(marginalia-off                     ((t (:foreground "#ff6347"))))
 '(marginalia-file-priv-dir           ((t (:foreground "#221199"))))
 '(marginalia-file-priv-exec          ((t (:foreground "#00a896"))))
 '(marginalia-file-priv-link          ((t (:foreground "#00a896"))))
 '(marginalia-file-priv-read          ((t (:foreground "#999999"))))
 '(marginalia-file-priv-write         ((t (:foreground "#ff6347"))))

 '(consult-file                       ((t (:foreground "#000000"))))
 '(consult-bookmark                   ((t (:foreground "#221199"))))
 '(consult-async-running              ((t (:foreground "#221199"))))
 '(consult-async-finished             ((t (:foreground "#00a896"))))
 '(consult-async-failed               ((t (:foreground "#ff6347"))))
 '(consult-async-split                ((t (:foreground "#999999"))))
 '(consult-narrow-indicator           ((t (:foreground "#221199" :weight bold))))
 '(consult-preview-line               ((t (:background "#f7f7f7"))))
 '(consult-preview-match              ((t (:background "#f0f0f0"))))
 '(consult-preview-cursor             ((t (:background "#e6e6e6"))))

 '(embark-keybinding                  ((t (:foreground "#221199"))))
 '(embark-collect-marked              ((t (:background "#f0f0f0" :foreground "#000000"))))
 '(embark-verbose-indicator-title     ((t (:weight bold))))
 '(embark-selected                    ((t (:background "#f0f0f0"))))
 '(embark-target                      ((t (:foreground "#221199" :weight bold))))

 '(ivy-current-match                  ((t (:background "#f0f0f0"))))
 '(ivy-minibuffer-match-face-1        ((t (:background "#e6e6e6"))))
 '(helm-selection                     ((t (:background "#f0f0f0"))))
 '(helm-match                         ((t (:foreground "#221199" :weight bold))))

 '(term-color-black                   ((t (:foreground "#000000" :background "#000000"))))
 '(term-color-red                     ((t (:foreground "#ff6347" :background "#ff6347"))))
 '(term-color-green                   ((t (:foreground "#00a896" :background "#00a896"))))
 '(term-color-yellow                  ((t (:foreground "#999999" :background "#999999"))))
 '(term-color-blue                    ((t (:foreground "#221199" :background "#221199"))))
 '(term-color-magenta                 ((t (:foreground "#221199" :background "#221199"))))
 '(term-color-cyan                    ((t (:foreground "#00a896" :background "#00a896"))))
 '(term-color-white                   ((t (:foreground "#f0f0f0" :background "#f0f0f0"))))

 '(rainbow-delimiters-depth-1-face    ((t (:foreground "#000000"))))
 '(rainbow-delimiters-depth-2-face    ((t (:foreground "#999999"))))
 '(rainbow-delimiters-depth-3-face    ((t (:foreground "#221199"))))
 '(rainbow-delimiters-depth-4-face    ((t (:foreground "#00a896"))))
 '(rainbow-delimiters-depth-5-face    ((t (:foreground "#000000"))))
 '(rainbow-delimiters-depth-6-face    ((t (:foreground "#999999"))))
 '(rainbow-delimiters-depth-7-face    ((t (:foreground "#221199"))))
 '(rainbow-delimiters-depth-8-face    ((t (:foreground "#00a896"))))
 '(rainbow-delimiters-depth-9-face    ((t (:foreground "#aaaaaa"))))
 '(rainbow-delimiters-unmatched-face  ((t (:foreground "#ffffff" :background "#ff6347"))))

 '(lsp-face-highlight-textual         ((t (:background "#f0f0f0"))))
 '(lsp-face-highlight-read            ((t (:background "#f0f0f0"))))
 '(lsp-face-highlight-write           ((t (:background "#f0f0f0" :underline t))))
 '(lsp-ui-doc-background              ((t (:background "#f0f0f0"))))
 '(lsp-ui-peek-selection              ((t (:background "#e6e6e6"))))
 '(lsp-ui-sideline-code-action        ((t (:foreground "#00a896"))))
 '(lsp-face-semhl-operator            ((t (:foreground "#000000"))))
 '(lsp-face-semhl-constant            ((t (:foreground "#221199"))))
 '(lsp-inlay-hint-face                ((t (:foreground "#aaaaaa"))))

 '(which-key-key-face                 ((t (:foreground "#221199"))))
 '(which-key-separator-face           ((t (:foreground "#aaaaaa"))))
 '(which-key-command-description-face ((t (:foreground "#000000"))))
 '(which-key-group-description-face   ((t (:foreground "#000000" :weight bold))))

 '(treemacs-root-face                 ((t (:foreground "#000000" :weight bold :height 1.2))))
 '(treemacs-directory-face            ((t (:foreground "#000000"))))
 '(treemacs-file-face                 ((t (:foreground "#000000"))))
 '(treemacs-tags-face                 ((t (:foreground "#221199"))))
 '(treemacs-fringe-indicator-face     ((t (:foreground "#221199"))))
 '(treemacs-git-added-face            ((t (:foreground "#00a896"))))
 '(treemacs-git-modified-face         ((t (:foreground "#221199"))))
 '(treemacs-git-conflict-face         ((t (:foreground "#ff6347"))))
 '(treemacs-git-untracked-face        ((t (:foreground "#00a896"))))
 '(treemacs-git-renamed-face          ((t (:foreground "#221199"))))
 '(treemacs-git-ignored-face          ((t (:foreground "#aaaaaa"))))
 '(treemacs-on-success-pulse-face     ((t (:background "#00a896" :foreground "#ffffff" :extend t))))
 '(treemacs-on-failure-pulse-face     ((t (:background "#ff6347" :foreground "#ffffff" :extend t))))

 '(window-divider                     ((t (:inherit vertical-border))))
 '(window-divider-first-pixel         ((t (:inherit window-divider))))
 '(window-divider-last-pixel          ((t (:inherit window-divider))))

 ;; elfeed
 '(elfeed-log-debug-level-face        ((t (:foreground "#999999"))))
 '(elfeed-log-error-level-face        ((t (:inherit error))))
 '(elfeed-log-info-level-face         ((t (:inherit success))))
 '(elfeed-log-warn-level-face         ((t (:inherit warning))))
 '(elfeed-search-date-face            ((t (:foreground "#999999"))))
 '(elfeed-search-feed-face            ((t (:foreground "#221199"))))
 '(elfeed-search-filter-face          ((t (:foreground "#221199"))))
 '(elfeed-search-last-modified-face   ((t (:foreground "#999999"))))
 '(elfeed-search-tag-face             ((t (:foreground "#999999"))))
 '(elfeed-search-title-face           ((t (:foreground "#999999"))))
 '(elfeed-search-unread-count-face    ((t (:foreground "#00a896"))))
 '(elfeed-search-unread-title-face    ((t (:foreground "#000000" :weight bold))))

 ;; local preferences
 '(font-lock-variable-use-face        ((t (:foreground unspecified))))
 '(font-lock-property-use-face        ((t (:foreground unspecified))))
 '(lsp-face-semhl-property            ((t (:foreground unspecified))))
 '(lsp-face-semhl-member              ((t (:foreground unspecified))))
 '(lsp-face-semhl-variable            ((t (:foreground unspecified))))
 '(lsp-face-semhl-parameter           ((t (:foreground unspecified))))
 '(lsp-face-semhl-macro               ((t (:foreground "#221199"))))
 '(lsp-rust-analyzer-mutable-modifier-face ((t (:underline nil))))

 '(error                              ((t (:background "#ff6347" :foreground "#ffffff"))))
 '(warning                            ((t (:foreground "#00a896"))))
 '(success                            ((t (:foreground "#00a896")))))

(provide-theme 'photopic)

;;; photopic-theme.el ends here
