music_directory "/run/media/nil/64603C01603BD88E/Music"
playlist_directory "~/.local/share/mpd/playlists"
db_file "~/.local/share/mpd/tag_cache"
state_file "~/.local/share/mpd/state"
sticker_file "~/.local/share/mpd/sticker.sql"

bind_to_address "127.0.0.1"
port "6600"

auto_update "yes"

audio_output {
	type "pipewire"
	name "PipeWire"
}
