unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

let mapleader = ' '
" vim-sexp binds <LocalLeader>c and <LocalLeader>w, which would shadow <leader> groups.
let maplocalleader = ','
scriptencoding utf-8

set encoding=utf-8
set fileencoding=utf-8
set number
set relativenumber
set cursorline
set cursorlineopt=number
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set title
set autoindent
set smartindent
set hidden
set autoread
set laststatus=2
set belloff=all
set ttimeoutlen=10
set undofile
set undodir=~/.vim/undodir
if !isdirectory(expand(&undodir))
  call mkdir(expand(&undodir), 'p', 0700)
endif
set incsearch
set termguicolors
set scrolloff=8
set updatetime=50
set timeoutlen=500
set nobackup
set nohlsearch
set noswapfile
set nowrap
set signcolumn=yes
set completeopt=menu,menuone,noinsert
set shortmess+=c
set isfname+=@-@

nnoremap <silent> <ScrollWheelUp> k
nnoremap <silent> <ScrollWheelDown> j
nnoremap <silent> <ScrollWheelLeft> h
nnoremap <silent> <ScrollWheelRight> l

vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

nnoremap J mzJ`z
function! s:sixth_scroll(key) abort
  return max([1, winheight(0) / 6]) . a:key . 'zz'
endfunction
nnoremap <expr> <C-d> <SID>sixth_scroll("\<C-d>")
nnoremap <expr> <C-u> <SID>sixth_scroll("\<C-u>")
nnoremap n nzzzv
nnoremap N Nzzzv

" Hold Alt+. / Alt+, to widen or narrow a window.
nnoremap <silent> <M-.> :<C-u>execute 'vertical resize +' . v:count1 * 5<CR>
nnoremap <silent> <M-,> :<C-u>execute 'vertical resize -' . v:count1 * 5<CR>

" This Vim has no Wayland clipboard of its own, so wl-clipboard backs the + and
" * registers.
function! s:wl_copy(register, type, lines) abort
  call system('wl-copy' . (a:register ==# '*' ? ' --primary' : ''), a:type ==# 'V' ? a:lines + [''] : a:lines)
endfunction

function! s:wl_paste(register) abort
  let l:text = system('wl-paste --no-newline' . (a:register ==# '*' ? ' --primary' : ''))
  if v:shell_error
    return []
  endif
  let l:lines = split(l:text, "\n", 1)
  return l:text =~# "\n$" ? ['V', l:lines[:-2]] : ['v', l:lines]
endfunction

let v:clipproviders['wl'] = {
      \ 'available': {-> !empty($WAYLAND_DISPLAY) && executable('wl-copy')},
      \ 'copy': { '+': function('s:wl_copy'), '*': function('s:wl_copy') },
      \ 'paste': { '+': function('s:wl_paste'), '*': function('s:wl_paste') },
      \ }
set clipmethod^=wl

" foot's Control+Shift+c copies only its own selection and never reaches Vim,
" so a mouse selection is copied when the drag ends and a keyboard selection
" when visual mode ends without changing or yanking anything.
let s:yanks = 0
let s:visual = {}

function! s:copy_finished_visual() abort
  if mode() =~# "^[vV\<C-v>]"
    let s:visual = { 'buffer': bufnr(), 'tick': b:changedtick, 'yanks': s:yanks }
    return
  endif
  let l:visual = s:visual
  let s:visual = {}
  if mode() ==# 'n' && l:visual ==# { 'buffer': bufnr(), 'tick': b:changedtick, 'yanks': s:yanks }
    let l:view = winsaveview()
    normal! gv"+y
    call winrestview(l:view)
  endif
endfunction

augroup clipboard
  autocmd!
  autocmd TextYankPost * let s:yanks += 1
  autocmd SafeState * ++nested call s:copy_finished_visual()
augroup END

xnoremap <silent> <LeftRelease> <LeftRelease>"+ygv

xnoremap <leader>p "_dP
nnoremap <leader>y "+y
vnoremap <leader>y "+y
nnoremap <leader>Y "+Y
nnoremap <leader>d "_d
vnoremap <leader>d "_d

inoremap <C-c> <Esc>
nnoremap Q <Nop>
nnoremap <silent> <C-f> :<C-u>call system('tmux neww tmux-sessionizer')<CR>

nnoremap <silent> <C-k> :<C-u>cnext<CR>zz
nnoremap <silent> <C-j> :<C-u>cprev<CR>zz
nnoremap <silent> <leader>k :<C-u>lnext<CR>zz
nnoremap <silent> <leader>j :<C-u>lprev<CR>zz

nnoremap <C-s> :%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>
nnoremap <silent> <leader>x :<C-u>call system('chmod +x ' . shellescape(expand('%')))<CR>

nnoremap <silent> <leader>u :<C-u>UndotreeToggle<CR>

nnoremap <silent> <leader>pv :<C-u>Explore<CR>
nnoremap <silent> <leader>pt :<C-u>NERDTreeToggle<CR>

let g:netrw_banner = 0

let g:NERDTreeWinPos = 'right'
let g:NERDTreeWinSize = 40
let g:NERDTreeShowHidden = 1
let g:NERDTreeMinimalUI = 1
let g:NERDTreeMouseMode = 3
let g:NERDTreeHijackNetrw = 0

augroup nerdtree-quit
  autocmd!
  autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree()
        \ | call feedkeys(":quit\<CR>:\<BS>") | endif
augroup END

let $FZF_DEFAULT_COMMAND = 'rg --files --hidden --glob "!**/.git/*" --glob "!node_modules/*"'
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.8, 'border': 'sharp' } }
let g:fzf_colors = {
      \ 'fg': ['fg', 'Normal'],
      \ 'bg': ['bg', 'Normal'],
      \ 'hl': ['fg', 'Function'],
      \ 'fg+': ['fg', 'Normal'],
      \ 'bg+': ['bg', 'Visual'],
      \ 'hl+': ['fg', 'Function'],
      \ 'info': ['fg', 'Comment'],
      \ 'border': ['fg', 'Comment'],
      \ 'prompt': ['fg', 'Keyword'],
      \ 'pointer': ['fg', 'Type'],
      \ 'marker': ['fg', 'String'],
      \ 'spinner': ['fg', 'Comment'],
      \ 'header': ['fg', 'Comment'],
      \ }

let s:rg = 'rg --column --line-number --no-heading --color=always --smart-case --hidden --glob "!**/.git/*" '

function! s:live_grep() abort
  call fzf#vim#grep2(s:rg . '-- ', '', fzf#vim#with_preview())
endfunction

function! s:grep_word() abort
  call fzf#vim#grep(s:rg . '--fixed-strings -- ' . fzf#shellescape(expand('<cword>')), fzf#vim#with_preview())
endfunction

nnoremap <silent> <leader>sh :<C-u>Helptags<CR>
nnoremap <silent> <leader>sk :<C-u>Maps<CR>
nnoremap <silent> <leader>sf :<C-u>Files<CR>
nnoremap <silent> <leader>ss :<C-u>Commands<CR>
nnoremap <silent> <leader>sw :<C-u>call <SID>grep_word()<CR>
nnoremap <silent> <leader>sg :<C-u>call <SID>live_grep()<CR>
nnoremap <silent> <leader>sd :<C-u>LspDocumentDiagnostics --buffers=*<CR>
nnoremap <silent> <leader>s. :<C-u>History<CR>
nnoremap <silent> <leader><leader> :<C-u>Buffers<CR>
nnoremap <silent> <leader>/ :<C-u>BLines<CR>
nnoremap <silent> <leader>s/ :<C-u>Lines<CR>
nnoremap <silent> <leader>sn :<C-u>execute 'Files' fnameescape(fnamemodify(resolve(expand('~/.vim/vimrc')), ':h'))<CR>

let g:asyncomplete_auto_completeopt = 0
let g:asyncomplete_popup_delay = 50

inoremap <expr> <Tab> pumvisible() ? asyncomplete#close_popup() : "\<Tab>"
imap <C-@> <Plug>(asyncomplete_force_refresh)
imap <expr> <C-l> vsnip#available(1) ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'
smap <expr> <C-l> vsnip#available(1) ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'
imap <expr> <C-h> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<C-h>'
smap <expr> <C-h> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<C-h>'

augroup completion
  autocmd!
  autocmd User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({
        \ 'name': 'file',
        \ 'allowlist': ['*'],
        \ 'priority': 10,
        \ 'completor': function('asyncomplete#sources#file#completor'),
        \ }))
augroup END

" raco packages (racket-langserver, fmt) install per user outside the Nix store.
function! s:raco_pkg(name) abort
  return !empty(glob('~/.local/share/racket/*/pkgs/' . a:name))
endfunction

let g:sexp_filetypes = 'clojure,scheme,lisp,racket,fennel'

let g:slime_target = 'vimterminal'
let g:slime_vimterminal_config = { 'vertical': 1, 'term_cols': 70, 'term_finish': 'close' }

let g:neoformat_only_msg_on_error = 1
let g:neoformat_try_node_exe = 1
let g:neoformat_enabled_elixir = ['mixformat']
let g:neoformat_enabled_go = ['gofmt']
let g:neoformat_enabled_nix = ['nixfmt']
let g:neoformat_racket_racofmt = { 'exe': 'raco', 'args': ['fmt'], 'stdin': 1 }
if s:raco_pkg('fmt')
  let g:neoformat_enabled_racket = ['racofmt']
endif
let g:neoformat_enabled_rust = ['rustfmt']
let g:neoformat_enabled_scala = ['scalafmt']
let g:neoformat_enabled_typescript = ['prettier']
let g:neoformat_enabled_typescriptreact = ['prettier']

function! s:format() abort
  if !exists('g:neoformat_enabled_' . &filetype)
    return
  endif
  try
    undojoin
    Neoformat
  catch /E790/
    Neoformat
  endtry
endfunction

augroup format-on-save
  autocmd!
  autocmd BufWritePre * call s:format()
augroup END

let g:lsp_diagnostics_virtual_text_enabled = 1
let g:lsp_diagnostics_virtual_text_prefix = ' '
let g:lsp_diagnostics_virtual_text_align = 'after'
let g:lsp_diagnostics_virtual_text_wrap = 'truncate'
let g:lsp_diagnostics_signs_error = { 'text': 'E' }
let g:lsp_diagnostics_signs_warning = { 'text': 'W' }
let g:lsp_diagnostics_signs_information = { 'text': 'I' }
let g:lsp_diagnostics_signs_hint = { 'text': 'H' }
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_document_code_action_signs_enabled = 0
let g:lsp_format_sync_timeout = 1000

function! s:command(command) abort
  return {_ -> executable(a:command[0]) ? a:command : []}
endfunction

function! s:root(markers) abort
  return {_ -> lsp#utils#path_to_uri(s:nearest(a:markers + ['.git/']))}
endfunction

function! s:nearest(markers) abort
  let l:directory = lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), a:markers)
  return empty(l:directory) ? getcwd() : l:directory
endfunction

function! s:register_servers() abort
  call lsp#register_server({
        \ 'name': 'elixir-ls',
        \ 'cmd': s:command(['elixir-ls']),
        \ 'root_uri': s:root(['mix.exs']),
        \ 'allowlist': ['elixir', 'eelixir'],
        \ })
  call lsp#register_server({
        \ 'name': 'gopls',
        \ 'cmd': s:command(['gopls']),
        \ 'root_uri': s:root(['go.work', 'go.mod']),
        \ 'allowlist': ['go', 'gomod'],
        \ })
  call lsp#register_server({
        \ 'name': 'metals',
        \ 'cmd': s:command(['metals']),
        \ 'root_uri': s:root(['build.sbt', 'build.sc', 'build.mill']),
        \ 'initialization_options': {
        \   'statusBarProvider': 'show-message',
        \   'isHttpEnabled': v:true,
        \   'compilerOptions': { 'snippetAutoIndent': v:false },
        \ },
        \ 'allowlist': ['scala', 'sbt'],
        \ })
  call lsp#register_server({
        \ 'name': 'nixd',
        \ 'cmd': s:command(['nixd']),
        \ 'root_uri': s:root(['flake.nix']),
        \ 'workspace_config': { 'nixd': { 'formatting': { 'command': ['nixfmt'] } } },
        \ 'allowlist': ['nix'],
        \ })
  call lsp#register_server({
        \ 'name': 'racket-langserver',
        \ 'cmd': {_ -> s:raco_pkg('racket-langserver') ? ['racket', '-l', 'racket-langserver'] : []},
        \ 'root_uri': s:root(['info.rkt']),
        \ 'allowlist': ['racket'],
        \ })
  call lsp#register_server({
        \ 'name': 'rust-analyzer',
        \ 'cmd': s:command(['rust-analyzer']),
        \ 'root_uri': s:root(['Cargo.toml']),
        \ 'initialization_options': { 'cargo': { 'features': 'all' } },
        \ 'allowlist': ['rust'],
        \ })
  call lsp#register_server({
        \ 'name': 'typescript-language-server',
        \ 'cmd': s:command(['typescript-language-server', '--stdio']),
        \ 'root_uri': s:root(['tsconfig.json', 'jsconfig.json', 'package.json']),
        \ 'allowlist': ['javascript', 'javascriptreact', 'typescript', 'typescriptreact'],
        \ })
endfunction

function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  nmap <buffer> gd <Plug>(lsp-definition)
  nmap <buffer> gr <Plug>(lsp-references)
  nmap <buffer> grr <Plug>(lsp-references)
  nmap <buffer> gI <Plug>(lsp-implementation)
  nmap <buffer> gD <Plug>(lsp-declaration)
  nmap <buffer> K <Plug>(lsp-hover)
  nmap <buffer> <leader>D <Plug>(lsp-type-definition)
  nmap <buffer> <leader>ds <Plug>(lsp-document-symbol-search)
  nmap <buffer> <leader>ws <Plug>(lsp-workspace-symbol-search)
  nmap <buffer> <leader>rr <Plug>(lsp-rename)
  nmap <buffer> <leader>ca <Plug>(lsp-code-action)
  nmap <buffer> <leader>f <Plug>(lsp-document-format)
  nmap <buffer> ]d <Plug>(lsp-next-diagnostic)
  nmap <buffer> [d <Plug>(lsp-previous-diagnostic)
endfunction

augroup lsp-setup
  autocmd!
  autocmd User lsp_setup call s:register_servers()
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

let g:which_key_use_floating_win = 1
let g:which_key_map = {
      \ ' ': 'find buffers',
      \ '/': 'search buffer',
      \ 'D': 'type definition',
      \ 'Y': 'yank line to clipboard',
      \ 'd': 'delete to void',
      \ 'f': 'format',
      \ 'j': 'previous location',
      \ 'k': 'next location',
      \ 'u': 'undo tree',
      \ 'x': 'make executable',
      \ 'y': 'yank to clipboard',
      \ 'c': { 'name': '+code', 'a': 'action' },
      \ 'r': { 'name': '+refactor', 'r': 'rename' },
      \ 'w': { 'name': '+workspace', 's': 'symbols' },
      \ 'p': { 'name': '+project', 'v': 'view', 't': 'tree' },
      \ 's': {
      \   'name': '+search',
      \   '.': 'recent files',
      \   '/': 'open buffers',
      \   'd': 'diagnostics',
      \   'f': 'files',
      \   'g': 'grep',
      \   'h': 'help',
      \   'k': 'keymaps',
      \   'n': 'config files',
      \   's': 'commands',
      \   'w': 'current word',
      \ },
      \ }

let s:which_key_sexp_map = {
      \ '[': 'wrap form in [] (head)',
      \ ']': 'wrap form in [] (tail)',
      \ '{': 'wrap form in {} (head)',
      \ '}': 'wrap form in {} (tail)',
      \ '?': 'convolute',
      \ '@': 'splice',
      \ 'I': 'wrap form in () (tail)',
      \ 'O': 'raise element',
      \ 'W': 'wrap element in () (tail)',
      \ 'h': 'insert at form head',
      \ 'i': 'wrap form in () (head)',
      \ 'l': 'insert at form tail',
      \ 'o': 'raise form',
      \ 'w': 'wrap element in () (head)',
      \ 'e': {
      \   'name': '+element',
      \   '[': 'wrap in [] (head)',
      \   ']': 'wrap in [] (tail)',
      \   '{': 'wrap in {} (head)',
      \   '}': 'wrap in {} (tail)',
      \ },
      \ }

let s:which_key_racket_map = {
      \ 'e': { 'name': '+eval / element', 'e': 'send form', 'f': 'send top-level form' },
      \ 'r': { 'name': '+racket', 'r': 'REPL start / reload', 'm': 'raco make', 't': 'raco test', 'd': 'raco docs' },
      \ }

" <LocalLeader> only has mappings in these buffers, so only they get the popup.
function! s:local_which_key() abort
  let b:which_key_local_map = deepcopy(s:which_key_sexp_map)
  if &filetype ==# 'racket'
    call extend(b:which_key_local_map.e, s:which_key_racket_map.e)
    let b:which_key_local_map.r = deepcopy(s:which_key_racket_map.r)
  endif
  nnoremap <buffer> <silent> <LocalLeader> :<C-u>WhichKey maplocalleader<CR>
endfunction

augroup which-key
  autocmd!
  autocmd VimEnter * call which_key#register('<Space>', 'g:which_key_map')
  " A string is evaluated on each popup, so every buffer shows its own map.
  autocmd VimEnter * call which_key#register(maplocalleader, 'b:which_key_local_map')
  execute 'autocmd FileType' g:sexp_filetypes 'call s:local_which_key()'
augroup END
nnoremap <silent> <leader> :<C-u>WhichKey '<Space>'<CR>
vnoremap <silent> <leader> :<C-u>WhichKeyVisual '<Space>'<CR>

let g:markdown_fenced_languages = ['elixir', 'go', 'nix', 'racket', 'rust', 'scala', 'sh', 'typescript', 'vim']

packloadall
filetype off
filetype plugin indent on
syntax enable
colorscheme base16_default_dark_plain
