;;; base16-default-dark-plain-theme.el --- Plain Base16 Default Dark theme  -*- lexical-binding:t -*-

;;; Commentary:
;; Base16 Default Dark with the plain tweaks of the helix and vim themes:
;; darker background, dim comments, no italics, and variables and members
;; left in the default foreground.

;;; Code:

;;;###theme-autoload
(deftheme base16-default-dark-plain
  "Plain Base16 Default Dark theme."
  :background-mode 'dark
  :kind 'color-scheme
  :family 'base16)

(let ((base00 "#111111")
      (base01 "#282828")
      (base02 "#383838")
      (base03 "#585858")
      (base04 "#b8b8b8")
      (base05 "#d8d8d8")
      (base06 "#e8e8e8")
      (base07 "#f8f8f8")
      (base08 "#ab4642")
      (base09 "#dc9656")
      (base0A "#f7ca88")
      (base0B "#a1b56c")
      (base0C "#86c1b9")
      (base0D "#7cafc2")
      (base0E "#ba8baf")
      (base0F "#a16946"))
  (custom-theme-set-faces
   'base16-default-dark-plain

   `(default ((t (:background ,base00 :foreground ,base05))))
   `(cursor ((t (:background ,base05))))
   `(region ((t (:background ,base02 :extend t))))
   `(highlight ((t (:background ,base02))))
   `(hl-line ((t (:background ,base01 :extend t))))
   `(fringe ((t (:foreground ,base03 :background ,base00))))
   `(vertical-border ((t (:background ,base01 :foreground ,base01))))
   `(minibuffer-prompt ((t (:foreground ,base0D))))
   `(isearch ((t (:background ,base09 :foreground ,base01))))
   `(lazy-highlight ((t (:background ,base0A :foreground ,base01))))
   `(link ((t (:foreground ,base09 :underline t))))
   `(link-visited ((t (:foreground ,base0E :underline t))))
   `(button ((t (:inherit link))))
   `(header-line ((t (:inherit mode-line))))
   `(tooltip ((t (:background ,base01 :foreground ,base05))))
   `(secondary-selection ((t (:background ,base01 :extend t))))

   `(font-lock-builtin-face ((t (:foreground ,base0C))))
   `(font-lock-comment-face ((t (:foreground ,base03))))
   `(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
   `(font-lock-constant-face ((t (:foreground ,base09))))
   `(font-lock-doc-face ((t (:inherit font-lock-comment-face))))
   `(font-lock-function-name-face ((t (:foreground ,base0D))))
   `(font-lock-keyword-face ((t (:foreground ,base0E))))
   `(font-lock-negation-char-face ((t (:foreground ,base05))))
   `(font-lock-preprocessor-face ((t (:foreground ,base09))))
   `(font-lock-string-face ((t (:foreground ,base0B))))
   `(font-lock-type-face ((t (:foreground ,base0A))))
   `(font-lock-variable-name-face ((t (:foreground ,base05))))
   `(font-lock-warning-face ((t (:inherit warning))))

   `(font-lock-operator-face ((t (:foreground ,base05))))
   `(font-lock-punctuation-face ((t (:foreground ,base05))))
   `(font-lock-bracket-face ((t (:inherit font-lock-punctuation-face))))
   `(font-lock-delimiter-face ((t (:inherit font-lock-punctuation-face))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,base0C))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,base0C))))
   `(font-lock-escape-face ((t (:foreground ,base0C))))
   `(font-lock-function-call-face ((t (:inherit font-lock-function-name-face))))
   `(font-lock-misc-punctuation-face ((t (:inherit font-lock-punctuation-face))))
   `(font-lock-number-face ((t (:foreground ,base09))))
   `(font-lock-preprocessor-char-face ((t (:foreground ,base09))))
   `(font-lock-property-name-face ((t (:foreground ,base05))))
   `(font-lock-property-use-face ((t (:inherit font-lock-property-name-face))))
   `(font-lock-variable-use-face ((t (:inherit font-lock-variable-name-face))))

   `(mode-line ((t (:background ,base01 :foreground ,base04 :box nil))))
   `(mode-line-active ((t (:inherit mode-line))))
   `(mode-line-inactive ((t (:background ,base01 :foreground ,base03 :box nil))))
   `(mode-line-buffer-id ((t (:weight bold))))
   `(mode-line-emphasis ((t (:foreground ,base0D))))
   `(mode-line-highlight ((t (:inherit highlight))))
   `(header-line-highlight ((t (:inherit mode-line-highlight))))

   `(line-number ((t (:inherit default :foreground ,base03 :background ,base01 :weight normal :slant normal))))
   `(line-number-current-line ((t (:inherit default :foreground ,base04 :background ,base01 :weight bold :slant normal))))

   `(show-paren-match ((t (:foreground ,base0A :underline t))))
   `(show-paren-mismatch ((t (:foreground ,base00 :background ,base08))))

   `(match ((t (:background ,base0A :foreground ,base01))))
   `(query-replace ((t (:inherit isearch))))
   `(isearch-fail ((t (:background ,base08 :foreground ,base00))))

   `(error ((t (:foreground ,base08))))
   `(warning ((t (:foreground ,base09))))
   `(success ((t (:foreground ,base0B))))
   `(shadow ((t (:foreground ,base03))))
   `(escape-glyph ((t (:foreground ,base0C))))
   `(nobreak-space ((t (:inherit escape-glyph :underline t))))
   `(trailing-whitespace ((t (:background ,base08))))

   `(bold ((t (:weight bold))))
   `(italic ((t (:slant normal))))
   `(bold-italic ((t (:inherit (bold italic)))))

   `(window-divider ((t (:inherit vertical-border))))
   `(window-divider-first-pixel ((t (:inherit window-divider))))
   `(window-divider-last-pixel ((t (:inherit window-divider))))

   ;; Man
   `(Man-overstrike ((t (:inherit bold :foreground ,base0D))))
   `(Man-underline ((t (:inherit underline :foreground ,base0B))))
   `(woman-bold ((t (:inherit Man-overstrike))))
   `(woman-italic ((t (:inherit Man-underline))))

   ;; ansi
   `(ansi-color-black ((t (:foreground ,base00 :background ,base00))))
   `(ansi-color-red ((t (:foreground ,base08 :background ,base08))))
   `(ansi-color-green ((t (:foreground ,base0B :background ,base0B))))
   `(ansi-color-yellow ((t (:foreground ,base0A :background ,base0A))))
   `(ansi-color-blue ((t (:foreground ,base0D :background ,base0D))))
   `(ansi-color-magenta ((t (:foreground ,base0E :background ,base0E))))
   `(ansi-color-cyan ((t (:foreground ,base0C :background ,base0C))))
   `(ansi-color-white ((t (:foreground ,base05 :background ,base05))))
   `(ansi-color-bright-black ((t (:foreground ,base03 :background ,base03))))
   `(ansi-color-bright-red ((t (:foreground ,base08 :background ,base08))))
   `(ansi-color-bright-green ((t (:foreground ,base0B :background ,base0B))))
   `(ansi-color-bright-yellow ((t (:foreground ,base0A :background ,base0A))))
   `(ansi-color-bright-blue ((t (:foreground ,base0D :background ,base0D))))
   `(ansi-color-bright-magenta ((t (:foreground ,base0E :background ,base0E))))
   `(ansi-color-bright-cyan ((t (:foreground ,base0C :background ,base0C))))
   `(ansi-color-bright-white ((t (:foreground ,base07 :background ,base07))))

   ;; term
   `(term ((t (:foreground ,base05))))
   `(term-bold ((t (:weight bold))))
   `(term-color-black ((t (:foreground ,base00 :background ,base00))))
   `(term-color-red ((t (:foreground ,base08 :background ,base08))))
   `(term-color-green ((t (:foreground ,base0B :background ,base0B))))
   `(term-color-yellow ((t (:foreground ,base0A :background ,base0A))))
   `(term-color-blue ((t (:foreground ,base0D :background ,base0D))))
   `(term-color-magenta ((t (:foreground ,base0E :background ,base0E))))
   `(term-color-cyan ((t (:foreground ,base0C :background ,base0C))))
   `(term-color-white ((t (:foreground ,base05 :background ,base05))))

   ;; vterm
   `(vterm-color-black ((t (:foreground ,base00 :background ,base03))))
   `(vterm-color-red ((t (:foreground ,base08 :background ,base08))))
   `(vterm-color-green ((t (:foreground ,base0B :background ,base0B))))
   `(vterm-color-yellow ((t (:foreground ,base0A :background ,base0A))))
   `(vterm-color-blue ((t (:foreground ,base0D :background ,base0D))))
   `(vterm-color-magenta ((t (:foreground ,base0E :background ,base0E))))
   `(vterm-color-cyan ((t (:foreground ,base0C :background ,base0C))))
   `(vterm-color-white ((t (:foreground ,base05 :background ,base07))))

   ;; avy
   `(avy-background-face ((t (:foreground ,base03))))
   `(avy-lead-face ((t (:foreground ,base0D :weight bold :underline t))))
   `(avy-lead-face-0 ((t (:inherit avy-lead-face :foreground ,base0E))))
   `(avy-lead-face-1 ((t (:inherit avy-lead-face :foreground ,base0C))))
   `(avy-lead-face-2 ((t (:inherit avy-lead-face :foreground ,base0B))))

   ;; bookmark
   `(bookmark-face ((t (:foreground ,base0D))))

   ;; cider
   `(cider-debug-code-overlay-face ((t (:background ,base01))))
   `(cider-deprecated-face ((t (:background ,base01 :strike-through t))))
   `(cider-enlightened-face ((t (:inherit cider-result-overlay-face :box (:color ,base09 :line-width -1)))))
   `(cider-enlightened-local-face ((t (:foreground ,base09 :weight bold))))
   `(cider-error-highlight-face ((t (:underline (:color ,base08)))))
   `(cider-fringe-good-face ((t (:foreground ,base0B))))
   `(cider-instrumented-face ((t (:background ,base02))))
   `(cider-result-overlay-face ((t (:background ,base01 :box (:line-width -1 :color ,base02)))))
   `(cider-test-error-face ((t (:foreground ,base00 :background ,base09))))
   `(cider-test-failure-face ((t (:foreground ,base00 :background ,base08))))
   `(cider-test-success-face ((t (:foreground ,base00 :background ,base0B))))
   `(cider-traced-face ((t (:background ,base02))))
   `(cider-warning-highlight-face ((t (:underline (:color ,base09)))))

   ;; company
   `(company-tooltip ((t (:inherit tooltip))))
   `(company-tooltip-selection ((t (:background ,base04 :foreground ,base01))))
   `(company-tooltip-common ((t (:foreground ,base0D :weight bold))))
   `(company-scrollbar-fg ((t (:background ,base03))))
   `(company-scrollbar-bg ((t (:background ,base01))))

   ;; compilation
   `(compilation-error ((t (:inherit error :weight bold))))
   `(compilation-warning ((t (:inherit warning :slant normal))))
   `(compilation-info ((t (:inherit success))))
   `(compilation-line-number ((t (:foreground ,base03))))
   `(compilation-column-number ((t (:inherit font-lock-comment-face))))
   `(compilation-mode-line-exit ((t (:inherit compilation-info))))
   `(compilation-mode-line-fail ((t (:inherit compilation-error))))

   ;; consult
   `(consult-file ((t (:foreground ,base05))))
   `(consult-bookmark ((t (:foreground ,base0D))))
   `(consult-async-running ((t (:foreground ,base0D))))
   `(consult-async-finished ((t (:foreground ,base0B))))
   `(consult-async-failed ((t (:foreground ,base08))))
   `(consult-preview-line ((t (:background ,base01))))
   `(consult-preview-match ((t (:inherit lazy-highlight))))

   ;; corfu
   `(corfu-default ((t (:inherit tooltip))))
   `(corfu-current ((t (:background ,base04 :foreground ,base01))))
   `(corfu-bar ((t (:background ,base03))))
   `(corfu-border ((t (:background ,base02))))
   `(corfu-annotations ((t (:foreground ,base03))))
   `(corfu-deprecated ((t (:foreground ,base03 :strike-through t))))
   `(corfu-echo ((t (:foreground ,base03))))
   `(corfu-popupinfo ((t (:inherit tooltip))))

   ;; custom
   `(custom-button ((t (:foreground ,base05 :background ,base01 :box (:line-width 1 :color ,base02)))))
   `(custom-button-mouse ((t (:foreground ,base01 :background ,base04 :box (:line-width 1 :color ,base02)))))
   `(custom-button-pressed ((t (:foreground ,base01 :background ,base04 :box (:line-width 1 :color ,base02)))))
   `(custom-button-pressed-unraised ((t (:foreground ,base01 :background ,base0E))))
   `(custom-button-unraised ((t (:foreground ,base0E))))
   `(custom-changed ((t (:foreground ,base0D))))
   `(custom-comment ((t (:foreground ,base05 :background ,base01))))
   `(custom-comment-tag ((t (:foreground ,base03))))
   `(custom-group-subtitle ((t (:foreground ,base0D :weight bold))))
   `(custom-group-tag ((t (:foreground ,base0D :weight bold))))
   `(custom-group-tag-1 ((t (:foreground ,base0E :weight bold))))
   `(custom-invalid ((t (:foreground ,base08))))
   `(custom-modified ((t (:foreground ,base0D))))
   `(custom-saved ((t (:foreground ,base0B))))
   `(custom-set ((t (:foreground ,base0A))))
   `(custom-state ((t (:foreground ,base0B))))
   `(custom-themed ((t (:foreground ,base0A))))
   `(custom-variable-button ((t (:foreground ,base0B :underline t))))
   `(custom-variable-obsolete ((t (:foreground ,base03))))
   `(custom-variable-tag ((t (:foreground ,base0D))))
   `(custom-visibility ((t (:inherit link))))

   ;; diff
   `(diff-added ((t (:foreground ,base0B :background ,base01 :extend t))))
   `(diff-removed ((t (:foreground ,base08 :background ,base01 :extend t))))
   `(diff-changed ((t (:foreground ,base09 :background ,base01 :extend t))))
   `(diff-context ((t (:foreground ,base04))))
   `(diff-header ((t (:foreground ,base0D))))
   `(diff-file-header ((t (:foreground ,base0D :weight bold))))
   `(diff-hunk-header ((t (:foreground ,base03))))
   `(diff-indicator-added ((t (:foreground ,base0B))))
   `(diff-indicator-changed ((t (:foreground ,base09))))
   `(diff-indicator-removed ((t (:foreground ,base08))))
   `(diff-refine-added ((t (:foreground ,base0B :background ,base02))))
   `(diff-refine-changed ((t (:foreground ,base0D :background ,base02))))
   `(diff-refine-removed ((t (:foreground ,base08 :background ,base02))))
   `(diff-hl-insert ((t (:foreground ,base0B :background ,base00))))
   `(diff-hl-change ((t (:foreground ,base09 :background ,base00))))
   `(diff-hl-delete ((t (:foreground ,base08 :background ,base00))))

   ;; dired
   `(dired-directory ((t (:foreground ,base0D))))
   `(dired-symlink ((t (:foreground ,base0C))))
   `(dired-header ((t (:foreground ,base0D :weight bold))))
   `(dired-flagged ((t (:foreground ,base08))))
   `(dired-ignored ((t (:foreground ,base03))))
   `(dired-mark ((t (:foreground ,base09 :weight bold))))
   `(dired-marked ((t (:foreground ,base0A :weight bold))))
   `(dired-perm-write ((t (:foreground ,base05))))
   `(dired-warning ((t (:foreground ,base09))))
   `(dired-k-added ((t (:foreground ,base0B :weight bold))))
   `(dired-k-commited ((t (:foreground ,base0B :weight bold))))
   `(dired-k-directory ((t (:foreground ,base0D :weight bold))))
   `(dired-k-ignored ((t (:foreground ,base03 :weight bold))))
   `(dired-k-modified ((t (:foreground ,base09 :weight bold))))
   `(dired-k-untracked ((t (:foreground ,base0C :weight bold))))
   `(dired-subtree-depth-1-face ((t (:background ,base01))))
   `(dired-subtree-depth-2-face ((t (:background ,base01))))
   `(dired-subtree-depth-3-face ((t (:background ,base01))))
   `(dired-subtree-depth-4-face ((t (:background ,base01))))
   `(dired-subtree-depth-5-face ((t (:background ,base01))))
   `(dired-subtree-depth-6-face ((t (:background ,base01))))

   ;; ediff
   `(ediff-current-diff-A ((t (:foreground ,base08 :background ,base01 :extend t))))
   `(ediff-current-diff-B ((t (:foreground ,base0B :background ,base01 :extend t))))
   `(ediff-current-diff-C ((t (:foreground ,base0A :background ,base01 :extend t))))
   `(ediff-even-diff-A ((t (:background ,base01 :extend t))))
   `(ediff-even-diff-B ((t (:inherit ediff-even-diff-A))))
   `(ediff-even-diff-C ((t (:inherit ediff-even-diff-A))))
   `(ediff-fine-diff-A ((t (:inherit diff-refine-removed))))
   `(ediff-fine-diff-B ((t (:inherit diff-refine-added))))
   `(ediff-fine-diff-C ((t (:inherit diff-refine-changed))))
   `(ediff-odd-diff-A ((t (:inherit ediff-even-diff-A))))
   `(ediff-odd-diff-B ((t (:inherit ediff-odd-diff-A))))
   `(ediff-odd-diff-C ((t (:inherit ediff-odd-diff-A))))

   ;; elixir
   `(elixir-atom-face ((t (:foreground ,base0B))))
   `(elixir-attribute-face ((t (:foreground ,base09))))

   ;; eshell
   `(eshell-prompt ((t (:foreground ,base0D :weight bold))))
   `(eshell-ls-archive ((t (:foreground ,base0E))))
   `(eshell-ls-backup ((t (:foreground ,base03))))
   `(eshell-ls-clutter ((t (:foreground ,base08))))
   `(eshell-ls-directory ((t (:foreground ,base0D))))
   `(eshell-ls-executable ((t (:foreground ,base0B))))
   `(eshell-ls-missing ((t (:foreground ,base08))))
   `(eshell-ls-product ((t (:foreground ,base09))))
   `(eshell-ls-readonly ((t (:foreground ,base09))))
   `(eshell-ls-special ((t (:foreground ,base0E))))
   `(eshell-ls-symlink ((t (:foreground ,base0C))))
   `(eshell-ls-unreadable ((t (:foreground ,base03))))

   ;; flycheck
   `(flycheck-error ((t (:underline (:color ,base08)))))
   `(flycheck-warning ((t (:underline (:color ,base09)))))
   `(flycheck-info ((t (:underline (:color ,base0D)))))
   `(flycheck-fringe-error ((t (:inherit fringe :foreground ,base08))))
   `(flycheck-fringe-warning ((t (:inherit fringe :foreground ,base09))))
   `(flycheck-fringe-info ((t (:inherit fringe :foreground ,base0D))))
   `(flycheck-posframe-face ((t (:inherit default))))
   `(flycheck-posframe-background-face ((t (:background ,base01))))
   `(flycheck-posframe-error-face ((t (:inherit flycheck-posframe-face :foreground ,base08))))
   `(flycheck-posframe-warning-face ((t (:inherit flycheck-posframe-face :foreground ,base09))))
   `(flycheck-posframe-info-face ((t (:inherit flycheck-posframe-face :foreground ,base0D))))

   ;; flymake
   `(flymake-error ((t (:underline (:color ,base08)))))
   `(flymake-warning ((t (:underline (:color ,base09)))))
   `(flymake-note ((t (:underline (:color ,base0D)))))

   ;; font-latex
   `(font-latex-bold-face ((t (:inherit bold :foreground ,base0A))))
   `(font-latex-italic-face ((t (:foreground ,base0E))))
   `(font-latex-math-face ((t (:foreground ,base0C))))
   `(font-latex-script-char-face ((t (:foreground ,base0C))))
   `(font-latex-sectioning-0-face ((t (:foreground ,base0D :weight bold))))
   `(font-latex-sectioning-1-face ((t (:foreground ,base0D :weight bold))))
   `(font-latex-sectioning-2-face ((t (:foreground ,base0D :weight bold))))
   `(font-latex-sectioning-3-face ((t (:foreground ,base0D :weight bold))))
   `(font-latex-sectioning-4-face ((t (:foreground ,base0D :weight bold))))
   `(font-latex-sectioning-5-face ((t (:foreground ,base0D :weight bold))))
   `(font-latex-sedate-face ((t (:inherit font-lock-keyword-face))))
   `(font-latex-string-face ((t (:inherit font-lock-string-face))))
   `(font-latex-underline-face ((t (:inherit underline))))
   `(font-latex-verbatim-face ((t (:inherit fixed-pitch :foreground ,base0B))))
   `(font-latex-warning-face ((t (:inherit font-lock-warning-face))))

   ;; git
   `(git-commit-summary ((t (:foreground ,base0B))))
   `(git-commit-overlong-summary ((t (:inherit error))))
   `(git-commit-nonempty-second-line ((t (:inherit git-commit-overlong-summary))))
   `(git-commit-keyword ((t (:foreground ,base0C))))
   `(git-commit-pseudo-header ((t (:foreground ,base03))))
   `(git-commit-known-pseudo-header ((t (:foreground ,base03 :weight bold))))
   `(git-commit-comment-heading ((t (:foreground ,base0E))))
   `(git-commit-comment-file ((t (:foreground ,base0D))))
   `(git-commit-comment-branch-local ((t (:foreground ,base0C))))
   `(git-commit-comment-branch-remote ((t (:foreground ,base0B))))
   `(git-commit-comment-detached ((t (:foreground ,base09))))
   `(git-gutter:added ((t (:inherit fringe :foreground ,base0B))))
   `(git-gutter:modified ((t (:inherit fringe :foreground ,base09))))
   `(git-gutter:deleted ((t (:inherit fringe :foreground ,base08))))
   `(git-gutter+-added ((t (:inherit fringe :foreground ,base0B))))
   `(git-gutter+-modified ((t (:inherit fringe :foreground ,base09))))
   `(git-gutter+-deleted ((t (:inherit fringe :foreground ,base08))))
   `(git-gutter-fr:added ((t (:inherit fringe :foreground ,base0B))))
   `(git-gutter-fr:modified ((t (:inherit fringe :foreground ,base09))))
   `(git-gutter-fr:deleted ((t (:inherit fringe :foreground ,base08))))

   ;; hi-lock
   `(hi-blue ((t (:foreground ,base00 :background ,base0D))))
   `(hi-blue-b ((t (:foreground ,base0D :weight bold))))
   `(hi-green ((t (:foreground ,base00 :background ,base0B))))
   `(hi-green-b ((t (:foreground ,base0B :weight bold))))
   `(hi-pink ((t (:foreground ,base00 :background ,base0E))))
   `(hi-red-b ((t (:foreground ,base08 :weight bold))))
   `(hi-yellow ((t (:foreground ,base00 :background ,base0A))))

   ;; highlight
   `(highlight-indentation-face ((t (:background ,base01))))
   `(highlight-indentation-current-column-face ((t (:background ,base02))))
   `(highlight-indentation-guides-even-face ((t (:inherit highlight-indentation-face))))
   `(highlight-indentation-guides-odd-face ((t (:inherit highlight-indentation-face))))
   `(highlight-numbers-number ((t (:foreground ,base09))))
   `(highlight-quoted-quote ((t (:foreground ,base05))))
   `(highlight-quoted-symbol ((t (:foreground ,base09))))
   `(highlight-symbol-face ((t (:background ,base02))))
   `(highlight-thing ((t (:background ,base02))))

   ;; hl
   `(hl-fill-column-face ((t (:background ,base01))))
   `(hl-todo ((t (:foreground ,base0A :weight bold))))

   ;; imenu
   `(imenu-list-entry-face-0 ((t (:foreground ,base0D))))
   `(imenu-list-entry-face-1 ((t (:foreground ,base0B))))
   `(imenu-list-entry-face-2 ((t (:foreground ,base0A))))
   `(imenu-list-entry-subalist-face-0 ((t (:inherit imenu-list-entry-face-0 :weight bold))))
   `(imenu-list-entry-subalist-face-1 ((t (:inherit imenu-list-entry-face-1 :weight bold))))
   `(imenu-list-entry-subalist-face-2 ((t (:inherit imenu-list-entry-face-2 :weight bold))))

   ;; indent
   `(indent-guide-face ((t (:foreground ,base02))))

   ;; ivy and helm
   `(ivy-current-match ((t (:background ,base02 :extend t))))
   `(ivy-minibuffer-match-face-1 ((t (:foreground ,base03))))
   `(helm-selection ((t (:background ,base02 :extend t))))
   `(helm-match ((t (:foreground ,base0D :weight bold))))

   ;; js2
   `(js2-function-param ((t (:foreground ,base05))))
   `(js2-function-call ((t (:foreground ,base0D))))
   `(js2-object-property ((t (:foreground ,base05))))
   `(js2-jsdoc-tag ((t (:foreground ,base03))))
   `(js2-external-variable ((t (:foreground ,base05))))

   ;; lsp
   `(lsp-face-highlight-textual ((t (:background ,base02))))
   `(lsp-face-highlight-read ((t (:inherit lsp-face-highlight-textual))))
   `(lsp-face-highlight-write ((t (:inherit lsp-face-highlight-textual))))
   `(lsp-inlay-hint-face ((t (:foreground ,base03))))
   `(lsp-headerline-breadcrumb-separator-face ((t (:inherit shadow))))
   `(lsp-ui-doc-background ((t (:background ,base01))))
   `(lsp-ui-peek-filename ((t (:inherit mode-line-buffer-id))))
   `(lsp-ui-peek-header ((t (:foreground ,base05 :background ,base02 :weight bold))))
   `(lsp-ui-peek-highlight ((t (:inherit lazy-highlight))))
   `(lsp-ui-peek-line-number ((t (:foreground ,base03))))
   `(lsp-ui-peek-list ((t (:background ,base01))))
   `(lsp-ui-peek-peek ((t (:background ,base01))))
   `(lsp-ui-peek-selection ((t (:foreground ,base01 :background ,base04))))
   `(lsp-ui-sideline-code-action ((t (:foreground ,base0D))))
   `(lsp-ui-sideline-current-symbol ((t (:inherit highlight))))
   `(lsp-ui-sideline-symbol-info ((t (:foreground ,base03 :extend t))))

   ;; magit
   `(magit-branch-current ((t (:foreground ,base0D))))
   `(magit-branch-local ((t (:foreground ,base0C))))
   `(magit-branch-remote ((t (:foreground ,base0B))))
   `(magit-branch-upstream ((t (:foreground ,base0B))))
   `(magit-tag ((t (:foreground ,base0A))))
   `(magit-hash ((t (:foreground ,base03))))
   `(magit-dimmed ((t (:foreground ,base03))))
   `(magit-filename ((t (:foreground ,base05))))
   `(magit-refname ((t (:foreground ,base03))))
   `(magit-header-line ((t (:inherit header-line :weight bold))))
   `(magit-section-heading ((t (:foreground ,base0D :weight bold :extend t))))
   `(magit-section-secondary-heading ((t (:foreground ,base0E :weight bold :extend t))))
   `(magit-section-highlight ((t (:background ,base01 :extend t))))
   `(magit-section-heading-selection ((t (:foreground ,base09 :weight bold :extend t))))
   `(magit-diff-file-heading ((t (:foreground ,base05 :weight bold :extend t))))
   `(magit-diff-file-heading-highlight ((t (:foreground ,base05 :background ,base01 :weight bold :extend t))))
   `(magit-diff-file-heading-selection ((t (:foreground ,base09 :background ,base01 :weight bold :extend t))))
   `(magit-diff-hunk-heading ((t (:foreground ,base04 :background ,base01 :extend t))))
   `(magit-diff-hunk-heading-highlight ((t (:foreground ,base05 :background ,base02 :extend t))))
   `(magit-diff-lines-heading ((t (:foreground ,base01 :background ,base09 :extend t))))
   `(magit-diff-context ((t (:foreground ,base03 :extend t))))
   `(magit-diff-context-highlight ((t (:foreground ,base04 :background ,base01 :extend t))))
   `(magit-diff-added ((t (:foreground ,base0B :extend t))))
   `(magit-diff-added-highlight ((t (:foreground ,base0B :background ,base01 :extend t))))
   `(magit-diff-removed ((t (:foreground ,base08 :extend t))))
   `(magit-diff-removed-highlight ((t (:foreground ,base08 :background ,base01 :extend t))))
   `(magit-diff-base ((t (:foreground ,base09 :extend t))))
   `(magit-diff-base-highlight ((t (:foreground ,base09 :background ,base01 :extend t))))
   `(magit-diffstat-added ((t (:foreground ,base0B))))
   `(magit-diffstat-removed ((t (:foreground ,base08))))
   `(magit-log-author ((t (:foreground ,base09))))
   `(magit-log-date ((t (:foreground ,base0D))))
   `(magit-log-graph ((t (:foreground ,base03))))
   `(magit-process-ok ((t (:inherit success))))
   `(magit-process-ng ((t (:inherit error))))
   `(magit-bisect-bad ((t (:foreground ,base08))))
   `(magit-bisect-good ((t (:foreground ,base0B))))
   `(magit-bisect-skip ((t (:foreground ,base09))))
   `(magit-blame-date ((t (:foreground ,base0D))))
   `(magit-blame-hash ((t (:foreground ,base03))))
   `(magit-blame-heading ((t (:foreground ,base04 :background ,base01 :extend t))))
   `(magit-cherry-equivalent ((t (:foreground ,base0E))))
   `(magit-cherry-unmatched ((t (:foreground ,base0C))))
   `(magit-reflog-amend ((t (:foreground ,base0E))))
   `(magit-reflog-checkout ((t (:foreground ,base0D))))
   `(magit-reflog-cherry-pick ((t (:foreground ,base0B))))
   `(magit-reflog-commit ((t (:foreground ,base0B))))
   `(magit-reflog-merge ((t (:foreground ,base0B))))
   `(magit-reflog-other ((t (:foreground ,base0C))))
   `(magit-reflog-rebase ((t (:foreground ,base0E))))
   `(magit-reflog-remote ((t (:foreground ,base0C))))
   `(magit-reflog-reset ((t (:inherit error))))
   `(magit-sequence-drop ((t (:foreground ,base08))))
   `(magit-sequence-head ((t (:foreground ,base0D))))
   `(magit-sequence-part ((t (:foreground ,base09))))
   `(magit-sequence-stop ((t (:foreground ,base0B))))
   `(magit-signature-bad ((t (:inherit error))))
   `(magit-signature-error ((t (:inherit error))))
   `(magit-signature-expired ((t (:foreground ,base09))))
   `(magit-signature-good ((t (:inherit success))))
   `(magit-signature-revoked ((t (:foreground ,base0E))))
   `(magit-signature-untrusted ((t (:foreground ,base0A))))

   ;; makefile
   `(makefile-targets ((t (:foreground ,base0D))))

   ;; marginalia
   `(marginalia-documentation ((t (:inherit font-lock-doc-face))))
   `(marginalia-key ((t (:foreground ,base0B))))
   `(marginalia-type ((t (:foreground ,base0E))))
   `(marginalia-char ((t (:foreground ,base0D))))
   `(marginalia-lighter ((t (:foreground ,base0E))))
   `(marginalia-on ((t (:foreground ,base0B))))
   `(marginalia-off ((t (:foreground ,base08))))
   `(marginalia-number ((t (:foreground ,base09))))
   `(marginalia-size ((t (:foreground ,base0E))))
   `(marginalia-file-priv-dir ((t (:foreground ,base0D))))
   `(marginalia-file-priv-exec ((t (:foreground ,base0B))))
   `(marginalia-file-priv-link ((t (:foreground ,base0C))))
   `(marginalia-file-priv-other ((t (:foreground ,base0E))))
   `(marginalia-file-priv-rare ((t (:foreground ,base05))))
   `(marginalia-file-priv-read ((t (:foreground ,base0A))))
   `(marginalia-file-priv-write ((t (:foreground ,base08))))

   ;; markdown
   `(markdown-header-face ((t (:foreground ,base0D))))
   `(markdown-header-delimiter-face ((t (:inherit markdown-header-face))))
   `(markdown-list-face ((t (:foreground ,base08))))
   `(markdown-bold-face ((t (:inherit bold :foreground ,base0A))))
   `(markdown-italic-face ((t (:foreground ,base0E))))
   `(markdown-link-face ((t (:foreground ,base08))))
   `(markdown-url-face ((t (:foreground ,base09 :underline t))))
   `(markdown-blockquote-face ((t (:foreground ,base0C))))
   `(markdown-code-face ((t (:foreground ,base0B :extend t))))
   `(markdown-pre-face ((t (:foreground ,base0B))))
   `(markdown-inline-code-face ((t (:inherit (markdown-code-face markdown-pre-face)))))
   `(markdown-markup-face ((t (:foreground ,base03))))
   `(markdown-metadata-key-face ((t (:foreground ,base08))))
   `(markdown-reference-face ((t (:foreground ,base03))))
   `(markdown-html-attr-name-face ((t (:foreground ,base09))))
   `(markdown-html-attr-value-face ((t (:inherit font-lock-string-face))))
   `(markdown-html-entity-face ((t (:foreground ,base0C))))
   `(markdown-html-tag-delimiter-face ((t (:inherit markdown-markup-face))))
   `(markdown-html-tag-name-face ((t (:foreground ,base08))))

   ;; mc/cursor
   `(mc/cursor-face ((t (:inherit cursor))))

   ;; message
   `(message-cited-text ((t (:foreground ,base0C))))
   `(message-cited-text-1 ((t (:foreground ,base0C))))
   `(message-cited-text-2 ((t (:foreground ,base0E))))
   `(message-cited-text-3 ((t (:foreground ,base0D))))
   `(message-cited-text-4 ((t (:foreground ,base0A))))
   `(message-header-name ((t (:foreground ,base0D))))
   `(message-header-subject ((t (:foreground ,base0A :weight bold))))
   `(message-header-to ((t (:foreground ,base0B))))
   `(message-header-cc ((t (:inherit message-header-to))))
   `(message-header-newsgroups ((t (:foreground ,base0A))))
   `(message-header-other ((t (:foreground ,base05))))
   `(message-header-xheader ((t (:foreground ,base03))))
   `(message-mml ((t (:foreground ,base03))))
   `(message-separator ((t (:foreground ,base03))))

   ;; org
   `(org-todo ((t (:foreground ,base0A :weight bold))))
   `(org-done ((t (:foreground ,base03 :weight bold))))
   `(org-headline-done ((t (:foreground ,base03))))
   `(org-date ((t (:foreground ,base0C))))
   `(org-link ((t (:inherit link))))
   `(org-block ((t (:background ,base01 :extend t))))
   `(org-block-background ((t (:background ,base01 :extend t))))
   `(org-block-begin-line ((t (:inherit org-block :foreground ,base03))))
   `(org-block-end-line ((t (:inherit org-block-begin-line))))
   `(org-code ((t (:foreground ,base0B))))
   `(org-verbatim ((t (:foreground ,base0B))))
   `(org-quote ((t (:inherit org-block :foreground ,base0C))))
   `(org-agenda-clocking ((t (:background ,base02))))
   `(org-agenda-date ((t (:foreground ,base0D :weight bold))))
   `(org-agenda-date-today ((t (:foreground ,base0D :weight bold :underline t))))
   `(org-agenda-date-weekend ((t (:foreground ,base03 :weight bold))))
   `(org-agenda-dimmed-todo-face ((t (:foreground ,base03))))
   `(org-agenda-done ((t (:inherit org-done))))
   `(org-agenda-structure ((t (:foreground ,base05 :weight bold))))
   `(org-archived ((t (:foreground ,base03))))
   `(org-checkbox ((t (:inherit org-todo))))
   `(org-checkbox-statistics-done ((t (:inherit org-done))))
   `(org-checkbox-statistics-todo ((t (:inherit org-todo))))
   `(org-cite ((t (:foreground ,base0C))))
   `(org-cite-key ((t (:foreground ,base0C :underline t))))
   `(org-default ((t (:inherit variable-pitch))))
   `(org-document-info ((t (:foreground ,base0D))))
   `(org-document-title ((t (:foreground ,base0D :weight bold))))
   `(org-drawer ((t (:foreground ,base03))))
   `(org-ellipsis ((t (:foreground ,base03))))
   `(org-footnote ((t (:foreground ,base09))))
   `(org-formula ((t (:foreground ,base0C))))
   `(org-hide ((t (:foreground ,base00))))
   `(org-latex-and-related ((t (:foreground ,base0C))))
   `(org-list-dt ((t (:foreground ,base0D))))
   `(org-meta-line ((t (:foreground ,base03))))
   `(org-priority ((t (:foreground ,base08))))
   `(org-property-value ((t (:foreground ,base03))))
   `(org-scheduled ((t (:foreground ,base05))))
   `(org-scheduled-previously ((t (:foreground ,base09))))
   `(org-scheduled-today ((t (:foreground ,base0B))))
   `(org-sexp-date ((t (:foreground ,base05))))
   `(org-special-keyword ((t (:foreground ,base03))))
   `(org-table ((t (:foreground ,base05))))
   `(org-tag ((t (:foreground ,base03 :weight normal))))
   `(org-time-grid ((t (:foreground ,base03))))
   `(org-upcoming-deadline ((t (:foreground ,base09))))
   `(org-upcoming-distant-deadline ((t (:foreground ,base04))))
   `(org-warning ((t (:foreground ,base08))))

   ;; outline
   `(outline-1 ((t (:foreground ,base0D :weight bold :extend t))))
   `(outline-2 ((t (:foreground ,base0D :weight bold :extend t))))
   `(outline-3 ((t (:foreground ,base0D :weight bold :extend t))))
   `(outline-4 ((t (:foreground ,base0D :weight bold :extend t))))
   `(outline-5 ((t (:foreground ,base0D :weight bold :extend t))))
   `(outline-6 ((t (:foreground ,base0D :weight bold :extend t))))
   `(outline-7 ((t (:foreground ,base0D :weight bold :extend t))))
   `(outline-8 ((t (:foreground ,base0D :weight bold :extend t))))

   ;; orderless
   `(orderless-match-face-0 ((t (:foreground ,base0D :weight bold))))
   `(orderless-match-face-1 ((t (:foreground ,base0E :weight bold))))
   `(orderless-match-face-2 ((t (:foreground ,base0B :weight bold))))
   `(orderless-match-face-3 ((t (:foreground ,base0A :weight bold))))

   ;; paren
   `(paren-face ((t (:foreground ,base03))))
   `(paren-face-match ((t (:inherit show-paren-match))))
   `(paren-face-mismatch ((t (:inherit show-paren-mismatch))))
   `(paren-face-no-match ((t (:inherit show-paren-mismatch))))

   ;; rainbow
   `(rainbow-delimiters-base-face ((t (:inherit default))))
   `(rainbow-delimiters-depth-1-face ((t (:foreground ,base0D))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,base0E))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,base0C))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,base0A))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,base0B))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,base09))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,base0D))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,base0E))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,base0C))))
   `(rainbow-delimiters-base-error-face ((t (:inherit rainbow-delimiters-base-face :foreground ,base08))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,base00 :background ,base08))))
   `(rainbow-delimiters-mismatched-face ((t (:inherit rainbow-delimiters-unmatched-face))))

   ;; sh
   `(sh-heredoc ((t (:inherit font-lock-string-face))))
   `(sh-quoted-exec ((t (:foreground ,base0C))))

   ;; smerge
   `(smerge-upper ((t (:background ,base01))))
   `(smerge-lower ((t (:background ,base01))))
   `(smerge-base ((t (:background ,base01))))
   `(smerge-mine ((t (:inherit smerge-upper))))
   `(smerge-other ((t (:inherit smerge-lower))))
   `(smerge-markers ((t (:foreground ,base03 :background ,base01))))
   `(smerge-refined-added ((t (:inherit diff-refine-added))))
   `(smerge-refined-removed ((t (:inherit diff-refine-removed))))

   ;; symbol-overlay
   `(symbol-overlay-default-face ((t (:background ,base02))))
   `(symbol-overlay-face-1 ((t (:foreground ,base00 :background ,base0D))))
   `(symbol-overlay-face-2 ((t (:foreground ,base00 :background ,base0E))))
   `(symbol-overlay-face-3 ((t (:foreground ,base00 :background ,base0A))))
   `(symbol-overlay-face-4 ((t (:foreground ,base00 :background ,base09))))
   `(symbol-overlay-face-5 ((t (:foreground ,base00 :background ,base08))))
   `(symbol-overlay-face-6 ((t (:foreground ,base00 :background ,base0C))))
   `(symbol-overlay-face-7 ((t (:foreground ,base00 :background ,base0B))))
   `(symbol-overlay-face-8 ((t (:foreground ,base00 :background ,base04))))

   ;; tab
   `(tab-bar ((t (:background ,base00 :foreground ,base04))))
   `(tab-bar-tab ((t (:background ,base01 :foreground ,base06))))
   `(tab-bar-tab-inactive ((t (:background ,base00 :foreground ,base04))))
   `(tab-line ((t (:background ,base00 :foreground ,base04))))
   `(tab-line-tab ((t (:background ,base01 :foreground ,base06))))
   `(tab-line-tab-current ((t (:background ,base01 :foreground ,base06))))
   `(tab-line-tab-inactive ((t (:background ,base00 :foreground ,base04))))
   `(tab-line-tab-inactive-alternate ((t (:inherit tab-line-tab-inactive))))
   `(tab-line-highlight ((t (:inherit tab-line-tab))))
   `(tab-line-close-highlight ((t (:foreground ,base08))))

   ;; treemacs
   `(treemacs-root-face ((t (:foreground ,base0D :weight bold))))
   `(treemacs-directory-face ((t (:foreground ,base0D))))
   `(treemacs-file-face ((t (:foreground ,base05))))
   `(treemacs-tags-face ((t (:foreground ,base0D))))
   `(treemacs-fringe-indicator-face ((t (:foreground ,base0D))))
   `(treemacs-git-added-face ((t (:foreground ,base0B))))
   `(treemacs-git-modified-face ((t (:foreground ,base09))))
   `(treemacs-git-conflict-face ((t (:foreground ,base08))))
   `(treemacs-git-untracked-face ((t (:foreground ,base0C))))
   `(treemacs-git-renamed-face ((t (:foreground ,base09))))
   `(treemacs-git-ignored-face ((t (:foreground ,base03))))
   `(treemacs-on-success-pulse-face ((t (:foreground ,base00 :background ,base0B :extend t))))
   `(treemacs-on-failure-pulse-face ((t (:foreground ,base00 :background ,base08 :extend t))))
   `(treemacs-nerd-icons-file-face ((t (:foreground ,base03))))
   `(treemacs-nerd-icons-root-face ((t (:inherit treemacs-root-face))))

   ;; typescript
   `(typescript-jsdoc-tag ((t (:foreground ,base03))))
   `(typescript-jsdoc-type ((t (:foreground ,base03))))
   `(typescript-jsdoc-value ((t (:foreground ,base03))))

   ;; vertico
   `(vertico-current ((t (:background ,base02 :extend t))))
   `(vertico-group-title ((t (:foreground ,base03 :weight bold))))
   `(vertico-group-separator ((t (:foreground ,base02 :strike-through t))))
   `(vertico-multiline ((t (:foreground ,base03))))
   `(vertico-quick1 ((t (:foreground ,base0D :weight bold))))
   `(vertico-quick2 ((t (:foreground ,base0B :weight bold))))
   `(vertico-posframe-border ((t (:background ,base02))))
   `(vertico-posframe-border-2 ((t (:background ,base08))))
   `(vertico-posframe-border-3 ((t (:background ,base0B))))
   `(vertico-posframe-border-4 ((t (:background ,base0D))))
   `(vertico-posframe-border-fallback ((t (:background ,base0A))))

   ;; web
   `(web-mode-html-tag-face ((t (:foreground ,base08))))
   `(web-mode-html-tag-bracket-face ((t (:foreground ,base05))))
   `(web-mode-html-attr-name-face ((t (:foreground ,base09))))
   `(web-mode-html-attr-value-face ((t (:foreground ,base0B))))
   `(web-mode-html-entity-face ((t (:foreground ,base0C))))
   `(web-mode-css-property-name-face ((t (:foreground ,base05))))
   `(web-mode-block-control-face ((t (:foreground ,base0E))))
   `(web-mode-block-delimiter-face ((t (:foreground ,base0F))))
   `(web-mode-doctype-face ((t (:foreground ,base03))))
   `(web-mode-json-context-face ((t (:foreground ,base05))))
   `(web-mode-json-key-face ((t (:foreground ,base05))))
   `(web-mode-keyword-face ((t (:foreground ,base0E))))
   `(web-mode-string-face ((t (:foreground ,base0B))))
   `(web-mode-type-face ((t (:foreground ,base0A))))

   ;; which
   `(which-func ((t (:foreground ,base0D))))
   `(which-key-key-face ((t (:foreground ,base0D))))
   `(which-key-separator-face ((t (:foreground ,base03))))
   `(which-key-group-description-face ((t (:foreground ,base0E))))
   `(which-key-command-description-face ((t (:foreground ,base05))))
   `(which-key-local-map-description-face ((t (:foreground ,base05))))

   ;; whitespace
   `(whitespace-empty ((t (:background ,base01))))
   `(whitespace-indentation ((t (:foreground ,base03 :background ,base01))))
   `(whitespace-line ((t (:foreground ,base08))))
   `(whitespace-newline ((t (:foreground ,base03))))
   `(whitespace-space ((t (:foreground ,base03))))
   `(whitespace-tab ((t (:foreground ,base03))))
   `(whitespace-trailing ((t (:inherit trailing-whitespace))))

   ;; widget
   `(widget-button-pressed ((t (:foreground ,base08))))
   `(widget-documentation ((t (:foreground ,base0B))))
   `(widget-field ((t (:background ,base01 :box (:line-width -1 :color ,base02) :extend t))))
   `(widget-single-line-field ((t (:background ,base01))))

   ;; window
   `(window-tool-bar-button ((t (:background ,base01 :foreground ,base05))))
   `(window-tool-bar-button-disabled ((t (:background ,base01 :foreground ,base03))))
   `(window-tool-bar-button-hover ((t (:inherit highlight))))

   ;; xref
   `(xref-file-header ((t (:foreground ,base0D))))
   `(xref-line-number ((t (:foreground ,base03))))
   `(xref-match ((t (:inherit match))))

   ;; yas
   `(yas-field-highlight-face ((t (:background ,base02))))

   ;; local preferences
   `(lsp-face-semhl-property ((t (:foreground unspecified))))
   `(lsp-face-semhl-member ((t (:foreground unspecified))))
   `(lsp-face-semhl-variable ((t (:foreground unspecified))))
   `(lsp-face-semhl-parameter ((t (:foreground unspecified))))
   `(lsp-face-semhl-namespace ((t (:foreground ,base0E))))
   `(lsp-face-semhl-macro ((t (:foreground ,base0D))))
   `(lsp-rust-analyzer-mutable-modifier-face ((t (:underline nil))))))

(provide-theme 'base16-default-dark-plain)

;;; base16-default-dark-plain-theme.el ends here
