;;; borealis-theme.el --- A dark theme inspired by Borealis  -*- lexical-binding:t -*-

;;; Commentary:
;; A dark theme inspired by the Borealis color palette.

;;; Code:

;;;###theme-autoload
(deftheme borealis
  "A dark theme inspired by borealis."
  :background-mode 'dark
  :kind 'color-scheme
  :family 'borealis)

(custom-theme-set-faces
 'borealis

 '(default ((t (:background "#282C33" :foreground "#EBECF0"))))
 '(cursor ((t (:background "#EBECF0"))))
 '(region ((t (:background "#3D424C"))))
 '(highlight ((t (:background "#272B3B"))))
 '(hl-line ((t (:background "#21252B"))))
 '(fringe ((t (:background unspecified))))
 '(vertical-border ((t (:foreground "#505562" :background "#282C33"))))
 '(minibuffer-prompt ((t (:foreground "#B2D8FA" :weight bold))))
 '(isearch ((t (:background "#5587b3" :foreground "#EBECF0"))))
 '(lazy-highlight ((t (:background "#3D424C"))))
 '(link ((t (:foreground "#B2D8FA" :underline t))))
 '(link-visited ((t (:foreground "#E7C7F9" :underline t))))
 '(button ((t (:inherit link))))
 '(header-line ((t (:background "#21252B" :foreground "#EBECF0"))))
 '(tooltip ((t (:background "#21252B" :foreground "#EBECF0"))))
 '(secondary-selection ((t (:background "#272B3B"))))

 '(font-lock-builtin-face ((t (:foreground "#E7C7F9"))))
 '(font-lock-comment-face ((t (:foreground "#A0A3AC" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#A0A3AC" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#D8A4F7"))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground "#C8CAD0"))))
 '(font-lock-function-name-face ((t (:foreground "#B2D8FA"))))
 '(font-lock-keyword-face ((t (:foreground "#BFEEC5" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#D8A4F7" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#F7B7B7" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#EEDDAF"))))
 '(font-lock-type-face ((t (:foreground "#C8FAF2"))))
 '(font-lock-variable-name-face ((t (:foreground unspecified))))
 '(font-lock-warning-face ((t (:foreground "#EEDDAF" :weight bold))))

 '(font-lock-operator-face ((t (:foreground "#EBECF0"))))
 '(font-lock-punctuation-face ((t (:foreground "#EBECF0"))))
 '(font-lock-bracket-face ((t (:foreground "#EBECF0"))))
 '(font-lock-delimiter-face ((t (:foreground "#EBECF0"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#F7B7B7"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#F7B7B7"))))

 '(mode-line ((t (:background "#1B1F26" :foreground "#EBECF0"))))
 '(mode-line-inactive ((t (:background "#21252B" :foreground "#A0A3AC"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#B2D8FA"))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "#505562")))))

 '(line-number ((t (:foreground "#505562" :background unspecified))))
 '(line-number-current-line ((t (:foreground "#EBECF0" :background unspecified :weight bold))))

 '(show-paren-match ((t (:background "#5587b3" :foreground "#EBECF0" :weight bold))))
 '(show-paren-mismatch ((t (:background "#F7B7B7" :foreground "#282C33"))))

 '(match ((t (:background "#3D424C"))))
 '(query-replace ((t (:inherit isearch))))

 '(diff-added ((t (:background "#1B3326" :foreground "#BFEEC5"))))
 '(diff-removed ((t (:background "#3B1B1B" :foreground "#F7B7B7"))))
 '(diff-changed ((t (:background "#3B3B1B" :foreground "#EEDDAF"))))
 '(diff-header ((t (:background "#21252B" :weight bold))))
 '(diff-file-header ((t (:background "#21252B" :foreground "#B2D8FA" :weight bold))))

 '(compilation-error ((t (:foreground "#F7B7B7" :weight bold))))
 '(compilation-warning ((t (:foreground "#EEDDAF" :weight bold))))
 '(compilation-info ((t (:foreground "#BFEEC5"))))
 '(compilation-line-number ((t (:foreground "#B2D8FA"))))

 '(org-level-1 ((t (:foreground "#BFEEC5" :weight bold))))
 '(org-level-2 ((t (:foreground "#BFEEC5" :weight bold))))
 '(org-level-3 ((t (:foreground "#BFEEC5" :weight bold))))
 '(org-level-4 ((t (:foreground "#BFEEC5"))))
 '(org-level-5 ((t (:foreground "#BFEEC5"))))
 '(org-level-6 ((t (:foreground "#BFEEC5"))))
 '(org-level-7 ((t (:foreground "#BFEEC5"))))
 '(org-level-8 ((t (:foreground "#BFEEC5"))))
 '(org-todo ((t (:foreground "#F7B7B7" :weight bold))))
 '(org-done ((t (:foreground "#BFEEC5" :weight bold))))
 '(org-headline-done ((t (:strike-through t))))
 '(org-date ((t (:foreground "#C8FAF2" :underline t))))
 '(org-link ((t (:foreground "#B2D8FA" :underline t))))
 '(org-block ((t (:background "#272B3B"))))
 '(org-block-begin-line ((t (:foreground "#A0A3AC" :background "#272B3B"))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-code ((t (:foreground "#E7C7F9"))))
 '(org-verbatim ((t (:foreground "#EEDDAF"))))

 '(outline-1 ((t (:foreground "#BFEEC5" :weight bold))))
 '(outline-2 ((t (:foreground "#B2D8FA" :weight bold))))
 '(outline-3 ((t (:foreground "#C8FAF2" :weight bold))))
 '(outline-4 ((t (:foreground "#EEDDAF" :weight bold))))
 '(outline-5 ((t (:foreground "#E7C7F9" :weight bold))))
 '(outline-6 ((t (:foreground "#D8A4F7" :weight bold))))
 '(outline-7 ((t (:foreground "#F7B7B7" :weight bold))))
 '(outline-8 ((t (:foreground "#F7D2B6" :weight bold))))

 '(dired-directory ((t (:foreground "#B2D8FA" :weight bold))))
 '(dired-symlink ((t (:foreground "#C8FAF2"))))
 '(dired-header ((t (:foreground "#EBECF0" :weight bold))))

 '(eshell-prompt ((t (:foreground "#B2D8FA" :weight bold))))
 '(eshell-ls-directory ((t (:foreground "#B2D8FA" :weight bold))))
 '(eshell-ls-executable ((t (:foreground "#BFEEC5"))))
 '(eshell-ls-symlink ((t (:foreground "#C8FAF2"))))

 '(company-tooltip ((t (:background "#21252B" :foreground "#EBECF0"))))
 '(company-tooltip-selection ((t (:background "#3D424C"))))
 '(company-tooltip-common ((t (:foreground "#B2D8FA"))))
 '(company-scrollbar-fg ((t (:background "#505562"))))
 '(company-scrollbar-bg ((t (:background "#272B3B"))))

 '(corfu-default ((t (:background "#21252B" :foreground "#EBECF0"))))
 '(corfu-current ((t (:background "#3D424C" :foreground "#EBECF0"))))
 '(corfu-bar ((t (:background "#505562"))))
 '(corfu-border ((t (:background "#3D424C"))))
 '(corfu-annotations ((t (:foreground "#A0A3AC"))))
 '(corfu-deprecated ((t (:foreground "#505562" :strike-through t))))
 '(corfu-echo ((t (:foreground "#A0A3AC"))))
 '(corfu-popupinfo ((t (:background "#21252B" :foreground "#EBECF0"))))

 '(flycheck-error ((t (:underline (:style wave :color "#F7B7B7")))))
 '(flycheck-warning ((t (:underline (:style wave :color "#EEDDAF")))))
 '(flycheck-info ((t (:underline (:style wave :color "#B2D8FA")))))

 '(git-gutter:added ((t (:foreground "#BFEEC5"))))
 '(git-gutter:deleted ((t (:foreground "#F7B7B7"))))
 '(git-gutter:modified ((t (:foreground "#F7D2B6"))))

 '(magit-branch-current ((t (:foreground "#B2D8FA" :weight bold))))
 '(magit-branch-local ((t (:foreground "#C8FAF2"))))
 '(magit-branch-remote ((t (:foreground "#BFEEC5"))))
 '(magit-branch-upstream ((t (:foreground "#BFEEC5"))))
 '(magit-tag ((t (:foreground "#EEDDAF"))))
 '(magit-hash ((t (:foreground "#A0A3AC"))))
 '(magit-section-heading ((t (:foreground "#B2D8FA" :weight bold))))
 '(magit-section-highlight ((t (:background "#272B3B"))))
 '(magit-section-heading-selection ((t (:background "#3D424C" :foreground "#F7B7B7"))))
 '(magit-diff-file-heading ((t (:background "#21252B" :foreground "#EBECF0"))))
 '(magit-diff-file-heading-highlight ((t (:background "#272B3B" :foreground "#EBECF0"))))
 '(magit-diff-hunk-heading ((t (:background "#272B3B" :foreground "#A0A3AC"))))
 '(magit-diff-hunk-heading-highlight ((t (:background "#3D424C" :foreground "#EBECF0"))))
 '(magit-diff-context ((t (:foreground "#EBECF0"))))
 '(magit-diff-context-highlight ((t (:background "#21252B" :foreground "#EBECF0"))))
 '(magit-diff-added ((t (:background "#1B3326" :foreground "#BFEEC5"))))
 '(magit-diff-added-highlight ((t (:background "#234430" :foreground "#BFEEC5"))))
 '(magit-diff-removed ((t (:background "#3B1B1B" :foreground "#F7B7B7"))))
 '(magit-diff-removed-highlight ((t (:background "#4B2323" :foreground "#F7B7B7"))))
 '(magit-diffstat-added ((t (:foreground "#BFEEC5"))))
 '(magit-diffstat-removed ((t (:foreground "#F7B7B7"))))
 '(magit-log-author ((t (:foreground "#C8FAF2"))))
 '(magit-log-date ((t (:foreground "#A0A3AC"))))
 '(magit-log-graph ((t (:foreground "#505562"))))
 '(magit-process-ok ((t (:foreground "#BFEEC5" :weight bold))))
 '(magit-process-ng ((t (:foreground "#F7B7B7" :weight bold))))

 '(vertico-current ((t (:background "#3D424C" :extend t))))
 '(vertico-group-title ((t (:background "#272B3B" :foreground "#A0A3AC" :weight bold))))
 '(vertico-group-separator ((t (:background "#272B3B" :foreground "#505562" :strike-through t))))
 '(vertico-multiline ((t (:foreground "#A0A3AC"))))
 '(vertico-quick1 ((t (:background "#21252B" :foreground "#B2D8FA" :weight bold))))
 '(vertico-quick2 ((t (:background "#21252B" :foreground "#BFEEC5" :weight bold))))

 '(orderless-match-face-0 ((t (:foreground "#B2D8FA" :weight bold))))
 '(orderless-match-face-1 ((t (:foreground "#BFEEC5" :weight bold))))
 '(orderless-match-face-2 ((t (:foreground "#EEDDAF" :weight bold))))
 '(orderless-match-face-3 ((t (:foreground "#E7C7F9" :weight bold))))

 '(marginalia-documentation ((t (:foreground "#A0A3AC" :slant italic))))
 '(marginalia-key ((t (:foreground "#BFEEC5"))))
 '(marginalia-type ((t (:foreground "#E7C7F9"))))
 '(marginalia-char ((t (:foreground "#B2D8FA"))))
 '(marginalia-lighter ((t (:foreground "#505562"))))
 '(marginalia-on ((t (:foreground "#BFEEC5"))))
 '(marginalia-off ((t (:foreground "#F7B7B7"))))

 '(consult-file ((t (:foreground "#EBECF0"))))
 '(consult-bookmark ((t (:foreground "#B2D8FA"))))
 '(consult-async-running ((t (:foreground "#B2D8FA"))))
 '(consult-async-finished ((t (:foreground "#BFEEC5"))))
 '(consult-async-failed ((t (:foreground "#F7B7B7"))))
 '(consult-preview-line ((t (:background "#272B3B"))))
 '(consult-preview-match ((t (:background "#3D424C"))))

 '(ivy-current-match ((t (:background "#5587b3" :foreground "#1B1F26"))))
 '(ivy-minibuffer-match-face-1 ((t (:background "#272B3B"))))
 '(helm-selection ((t (:background "#3D424C"))))
 '(helm-match ((t (:foreground "#B2D8FA" :weight bold))))

 '(term-color-black ((t (:foreground "#1B1F26" :background "#1B1F26"))))
 '(term-color-red ((t (:foreground "#F7B7B7" :background "#F7B7B7"))))
 '(term-color-green ((t (:foreground "#BFEEC5" :background "#BFEEC5"))))
 '(term-color-yellow ((t (:foreground "#EEDDAF" :background "#EEDDAF"))))
 '(term-color-blue ((t (:foreground "#B2D8FA" :background "#B2D8FA"))))
 '(term-color-magenta ((t (:foreground "#E7C7F9" :background "#E7C7F9"))))
 '(term-color-cyan ((t (:foreground "#C8FAF2" :background "#C8FAF2"))))
 '(term-color-white ((t (:foreground "#EBECF0" :background "#EBECF0"))))

 '(rainbow-delimiters-depth-1-face ((t (:foreground "#F7B7B7"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#F7D2B6"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#EEDDAF"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#BFEEC5"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#C8FAF2"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#B2D8FA"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#E7C7F9"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#D8A4F7"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#A6F8EB"))))

 '(lsp-face-highlight-textual ((t (:background "#3D424C"))))
 '(lsp-face-highlight-read ((t (:background "#3D424C"))))
 '(lsp-face-highlight-write ((t (:background "#3D424C" :underline t))))
 '(lsp-ui-doc-background ((t (:background "#21252B"))))
 '(lsp-ui-peek-selection ((t (:background "#3D424C"))))
 '(lsp-ui-sideline-code-action ((t (:foreground "#EEDDAF"))))
 '(lsp-face-semhl-operator ((t (:foreground "#EBECF0"))))
 '(lsp-face-semhl-constant ((t (:foreground "#D8A4F7" :weight bold))))
 '(lsp-face-semhl-namespace ((t (:foreground "#C8FAF2"))))
 '(lsp-inlay-hint-face ((t (:foreground "#505562"))))

 '(which-key-key-face ((t (:foreground "#BFEEC5"))))
 '(which-key-separator-face ((t (:foreground "#505562"))))
 '(which-key-command-description-face ((t (:foreground "#EBECF0"))))

 '(web-mode-html-tag-face ((t (:foreground "#E7C7F9"))))
 '(web-mode-html-attr-name-face ((t (:foreground "#F7D2B6"))))
 '(web-mode-html-attr-value-face ((t (:foreground "#EEDDAF"))))
 '(web-mode-css-selector-face ((t (:foreground "#B2D8FA"))))
 '(web-mode-css-property-name-face ((t (:foreground "#C8FAF2"))))

 '(js2-function-param ((t (:foreground "#EBECF0"))))
 '(js2-function-call ((t (:foreground "#B2D8FA"))))
 '(js2-object-property ((t (:foreground "#EBECF0"))))
 '(js2-jsdoc-tag ((t (:foreground "#C8CAD0"))))
 '(js2-external-variable ((t (:foreground "#EBECF0"))))

 '(markdown-header-face-1 ((t (:foreground "#BFEEC5" :weight bold))))
 '(markdown-header-face-2 ((t (:foreground "#BFEEC5" :weight bold))))
 '(markdown-header-face-3 ((t (:foreground "#BFEEC5" :weight bold))))
 '(markdown-header-face-4 ((t (:foreground "#BFEEC5"))))
 '(markdown-bold-face ((t (:foreground "#F7B7B7" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#F7B7B7" :slant italic))))
 '(markdown-link-face ((t (:foreground "#B2D8FA"))))
 '(markdown-url-face ((t (:foreground "#F7D2B6"))))
 '(markdown-code-face ((t (:background "#272B3B"))))
 '(markdown-blockquote-face ((t (:foreground "#B2D8FA" :slant italic))))

 '(treemacs-root-face ((t (:inherit font-lock-string-face :weight bold :height 1.2))))
 '(treemacs-directory-face ((t (:foreground "#EBECF0"))))
 '(treemacs-file-face ((t (:foreground "#EBECF0"))))
 '(treemacs-tags-face ((t (:foreground "#B2D8FA"))))
 '(treemacs-fringe-indicator-face ((t (:foreground "#B2D8FA"))))
 '(treemacs-git-added-face ((t (:foreground "#BFEEC5"))))
 '(treemacs-git-modified-face ((t (:foreground "#EEDDAF"))))
 '(treemacs-git-conflict-face ((t (:foreground "#F7B7B7"))))
 '(treemacs-git-untracked-face ((t (:foreground "#BFEEC5"))))
 '(treemacs-git-renamed-face ((t (:foreground "#EEDDAF"))))
 '(treemacs-git-ignored-face ((t (:foreground "#A0A3AC"))))
 '(treemacs-on-success-pulse-face ((t (:background "#BFEEC5" :foreground "#1B1F26" :extend t))))
 '(treemacs-on-failure-pulse-face ((t (:background "#F7B7B7" :foreground "#1B1F26" :extend t))))

 '(window-divider ((t (:inherit vertical-border))))
 '(window-divider-first-pixel ((t (:inherit window-divider))))
 '(window-divider-last-pixel ((t (:inherit window-divider))))

 ;; elfeed
 '(elfeed-log-debug-level-face ((t (:foreground "#A0A3AC"))))
 '(elfeed-log-error-level-face ((t (:inherit error))))
 '(elfeed-log-info-level-face ((t (:inherit success))))
 '(elfeed-log-warn-level-face ((t (:inherit warning))))
 '(elfeed-search-date-face ((t (:foreground "#D8A4F7"))))
 '(elfeed-search-feed-face ((t (:foreground "#B2D8FA"))))
 '(elfeed-search-filter-face ((t (:foreground "#D8A4F7"))))
 '(elfeed-search-last-modified-face ((t (:foreground "#A0A3AC"))))
 '(elfeed-search-tag-face ((t (:foreground "#A0A3AC"))))
 '(elfeed-search-title-face ((t (:foreground "#A0A3AC"))))
 '(elfeed-search-unread-count-face ((t (:foreground "#EEDDAF"))))
 '(elfeed-search-unread-title-face ((t (:foreground "#EBECF0" :weight bold))))

 ;; local preferences
 '(font-lock-variable-use-face ((t (:foreground unspecified))))
 '(lsp-face-semhl-property ((t (:foreground unspecified))))
 '(lsp-face-semhl-member ((t (:foreground unspecified))))
 '(lsp-face-semhl-variable ((t (:foreground unspecified))))
 '(lsp-face-semhl-parameter ((t (:foreground unspecified))))
 '(lsp-face-semhl-macro ((t (:foreground "#F7B7B7"))))
 '(lsp-rust-analyzer-mutable-modifier-face ((t (:underline nil))))

 '(error ((t (:foreground "#F7B7B7" :weight bold))))
 '(warning ((t (:foreground "#EEDDAF" :weight bold))))
 '(success ((t (:foreground "#BFEEC5" :weight bold)))))

(provide-theme 'borealis)

;;; borealis-theme.el ends here
