#!/bin/sh
systemctl --user import-environment PATH WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
hash dbus-update-activation-environment 2>/dev/null && \
  dbus-update-activation-environment --systemd PATH WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
systemctl --user restart xdg-desktop-portal-gtk.service xdg-desktop-portal.service &
theme-apply &
(
  exec 9>"${XDG_RUNTIME_DIR:-/tmp}/labwc-sfwbar.lock"
  if flock -n 9; then
    while pgrep -x labwc >/dev/null 2>&1; do
      sfwbar
      sleep 1
    done
  fi
) &
openrgb --mode static --color 000000 &
nm-applet &
solaar --window=hide &
pkill -f "tailscale systray"
tailscale systray &
pkill -x mullvad-vpn
mullvad-vpn &
gsettings set org.gnome.desktop.interface cursor-theme Adwaita
gsettings set org.gnome.desktop.interface cursor-size 16
gsettings set org.gnome.desktop.interface text-scaling-factor 1.25
swayidle -w \
  timeout 1800 'swaylock -f -c 4f5459' \
  before-sleep 'swaylock -f -c 4f5459' &
