;;;; pragmata-theme.el --- A bright neutral light theme  -*- lexical-binding:t -*-

;;; Commentary:

;; A bright, neutral light theme with cool gray tones.
;; Simple and focused on readability with minimal complexity.

;;; Code:

;;;###theme-autoload
(deftheme pragmata
  "A bright neutral light theme."
  :background-mode 'light
  :kind 'color-scheme
  :family 'pragmata)

(custom-theme-set-faces
 'pragmata
 '(default                            ((t (:background "#f5f5f5" :foreground "#000000"))))
 '(cursor                             ((t (:background "#404040"))))
 '(region                             ((t (:background "#d0d0d0"))))
 '(highlight                          ((t (:background "#e0e0e0"))))
 '(hl-line                            ((t (:background "#eeeeee"))))
 '(fringe                             ((t (:background nil))))
 '(vertical-border                    ((t (:foreground "#e8e8e8"))))
 '(minibuffer-prompt                  ((t (:foreground "#2981ca" :weight bold))))
 '(isearch                            ((t (:background "#a0a0a0" :foreground "#ffffff"))))
 '(lazy-highlight                     ((t (:background "#e0e0e0"))))
 '(link                               ((t (:foreground "#2981ca" :underline t))))
 '(link-visited                       ((t (:foreground "#9805AE" :underline t))))
 '(button                             ((t (:inherit link))))
 '(header-line                        ((t (:background "#e8e8e8" :foreground "#000000"))))
 '(tooltip                            ((t (:background "#e8e8e8" :foreground "#000000"))))
 '(secondary-selection                ((t (:background "#ececec"))))
 '(shadow                             ((t (:foreground "#606060"))))

 '(font-lock-builtin-face             ((t (:foreground "#000000" :weight bold))))
 '(font-lock-comment-face             ((t (:foreground "#194E00"))))
 '(font-lock-comment-delimiter-face   ((t (:foreground "#194E00"))))
 '(font-lock-constant-face            ((t (:foreground "#1e73be"))))
 '(font-lock-doc-face                 ((t (:foreground "#194E00" :slant italic))))
 '(font-lock-function-name-face       ((t (:foreground "#000000"))))
 '(font-lock-keyword-face             ((t (:foreground "#000000" :weight bold))))
 '(font-lock-negation-char-face       ((t (:foreground "#e41507"))))
 '(font-lock-preprocessor-face        ((t (:foreground "#e41507"))))
 '(font-lock-string-face              ((t (:foreground "#56283c"))))
 '(font-lock-type-face                ((t (:foreground "#1e73be" :weight regular))))
 '(font-lock-variable-name-face       ((t (:foreground "#000000"))))
 '(font-lock-warning-face             ((t (:foreground "#e41507" :weight bold))))

 '(font-lock-operator-face            ((t (:foreground "#e41507"))))
 '(font-lock-punctuation-face         ((t (:foreground "#e41507"))))
 '(font-lock-bracket-face             ((t (:foreground "#e41507"))))
 '(font-lock-delimiter-face           ((t (:foreground "#e41507"))))

 '(mode-line                          ((t (:background "#e8e8e8" :foreground "#000000" :box (:line-width 1 :color "#d0d0d0")))))
 '(mode-line-inactive                 ((t (:background "#ececec" :foreground "#505050" :box (:line-width 1 :color "#d0d0d0")))))
 '(mode-line-buffer-id                ((t (:weight bold))))
 '(mode-line-emphasis                 ((t (:weight bold))))
 '(mode-line-highlight                ((t (:box (:line-width 2 :color "#a0a0a0")))))

 '(line-number                        ((t (:foreground "#606060" :background "#f5f5f5"))))
 '(line-number-current-line           ((t (:foreground "#000000" :background "#f5f5f5" :weight bold))))

 '(show-paren-match                   ((t (:background "#e0e0e0" :weight bold))))
 '(show-paren-mismatch                ((t (:background "#ffc0c0" :foreground "#e41507"))))

 '(match                              ((t (:background "#e0e0e0"))))
 '(query-replace                      ((t (:inherit isearch))))

 '(diff-added                         ((t (:background "#e0ffe0" :foreground "#194E00"))))
 '(diff-removed                       ((t (:background "#ffe0e0" :foreground "#e41507"))))
 '(diff-changed                       ((t (:background "#ffffe0" :foreground "#9E7400"))))
 '(diff-header                        ((t (:background "#e8e8e8" :weight bold))))
 '(diff-file-header                   ((t (:background "#e8e8e8" :foreground "#2981ca" :weight bold))))

 '(compilation-error                  ((t (:foreground "#e41507" :weight bold))))
 '(compilation-warning                ((t (:foreground "#E6BB00" :weight bold))))
 '(compilation-info                   ((t (:foreground "#329033"))))
 '(compilation-line-number            ((t (:foreground "#2981ca"))))

 '(org-level-1                        ((t (:foreground "#000000" :weight bold))))
 '(org-level-2                        ((t (:foreground "#2981ca" :weight bold))))
 '(org-level-3                        ((t (:foreground "#329033" :weight bold))))
 '(org-level-4                        ((t (:foreground "#9E7400" :weight bold))))
 '(org-level-5                        ((t (:foreground "#2E998E" :weight bold))))
 '(org-level-6                        ((t (:foreground "#9805AE" :weight bold))))
 '(org-level-7                        ((t (:foreground "#e41507" :weight bold))))
 '(org-level-8                        ((t (:foreground "#505050" :weight bold))))
 '(org-todo                           ((t (:foreground "#e41507" :weight bold))))
 '(org-done                           ((t (:foreground "#329033" :weight bold))))
 '(org-date                           ((t (:foreground "#2981ca" :underline t))))
 '(org-link                           ((t (:inherit link))))
 '(org-block                          ((t (:background "#ececec"))))
 '(org-block-begin-line               ((t (:foreground "#a0a0a0" :background "#e8e8e8"))))
 '(org-block-end-line                 ((t (:inherit org-block-begin-line))))
 '(org-code                           ((t (:foreground "#000000" :background "#ececec"))))
 '(org-verbatim                       ((t (:foreground "#000000" :background "#ececec"))))

 '(outline-1                          ((t (:foreground "#000000" :weight bold))))
 '(outline-2                          ((t (:foreground "#2981ca" :weight bold))))
 '(outline-3                          ((t (:foreground "#329033" :weight bold))))
 '(outline-4                          ((t (:foreground "#9E7400" :weight bold))))
 '(outline-5                          ((t (:foreground "#2E998E" :weight bold))))
 '(outline-6                          ((t (:foreground "#9805AE" :weight bold))))
 '(outline-7                          ((t (:foreground "#e41507" :weight bold))))
 '(outline-8                          ((t (:foreground "#505050" :weight bold))))

 '(dired-directory                    ((t (:foreground "#2981ca" :weight bold))))
 '(dired-symlink                      ((t (:foreground "#2E998E"))))
 '(dired-header                       ((t (:foreground "#000000" :weight bold))))

 '(eshell-prompt                      ((t (:foreground "#2981ca" :weight bold))))
 '(eshell-ls-directory                ((t (:foreground "#2981ca" :weight bold))))
 '(eshell-ls-executable               ((t (:foreground "#329033"))))
 '(eshell-ls-symlink                  ((t (:foreground "#2E998E"))))

 '(corfu-default                      ((t (:background "#e8e8e8" :foreground "#000000"))))
 '(corfu-current                      ((t (:background "#d0d0d0" :foreground "#000000"))))
 '(corfu-bar                          ((t (:background "#a0a0a0"))))
 '(corfu-border                       ((t (:background "#c0c0c0"))))
 '(corfu-annotations                  ((t (:foreground "#505050"))))
 '(corfu-deprecated                   ((t (:foreground "#a0a0a0" :strike-through t))))
 '(corfu-echo                         ((t (:foreground "#505050"))))
 '(corfu-popupinfo                    ((t (:background "#e8e8e8" :foreground "#000000"))))
 '(cape-keyword                       ((t (:foreground "#000000" :weight bold))))

 '(company-tooltip                    ((t (:background "#e8e8e8" :foreground "#000000"))))
 '(company-tooltip-selection          ((t (:background "#d0d0d0"))))
 '(company-tooltip-common             ((t (:foreground "#2981ca"))))
 '(company-scrollbar-fg               ((t (:background "#a0a0a0"))))
 '(company-scrollbar-bg               ((t (:background "#ececec"))))

 '(flycheck-error                     ((t (:underline (:style wave :color "#e41507")))))
 '(flycheck-warning                   ((t (:underline (:style wave :color "#9E7400")))))
 '(flycheck-info                      ((t (:underline (:style wave :color "#2981ca")))))

 '(git-gutter:added                   ((t (:foreground "#329033"))))
 '(git-gutter:deleted                 ((t (:foreground "#e41507"))))
 '(git-gutter:modified                ((t (:foreground "#E6BB00"))))

 '(magit-branch-current               ((t (:foreground "#2981ca" :weight bold))))
 '(magit-branch-local                 ((t (:foreground "#2E998E"))))
 '(magit-branch-remote                ((t (:foreground "#329033"))))
 '(magit-branch-upstream              ((t (:foreground "#329033"))))
 '(magit-tag                          ((t (:foreground "#9E7400"))))
 '(magit-hash                         ((t (:foreground "#505050"))))
 '(magit-section-heading              ((t (:foreground "#2981ca" :weight bold))))
 '(magit-section-highlight            ((t (:background "#ececec"))))
 '(magit-section-heading-selection    ((t (:background "#e0e0e0" :foreground "#e41507"))))
 '(magit-diff-file-heading            ((t (:background "#e8e8e8" :foreground "#000000"))))
 '(magit-diff-file-heading-highlight  ((t (:background "#e0e0e0" :foreground "#000000"))))
 '(magit-diff-hunk-heading            ((t (:background "#ececec" :foreground "#505050"))))
 '(magit-diff-hunk-heading-highlight  ((t (:background "#e0e0e0" :foreground "#000000"))))
 '(magit-diff-hunk-heading-selection  ((t (:background "#d0d0d0" :foreground "#e41507"))))
 '(magit-diff-context                 ((t (:foreground "#000000"))))
 '(magit-diff-context-highlight       ((t (:background "#f0f0f0" :foreground "#000000"))))
 '(magit-diff-added                   ((t (:background "#e8ffe8" :foreground "#194E00"))))
 '(magit-diff-added-highlight         ((t (:background "#e0ffe0" :foreground "#194E00"))))
 '(magit-diff-removed                 ((t (:background "#ffe8e8" :foreground "#e41507"))))
 '(magit-diff-removed-highlight       ((t (:background "#ffe0e0" :foreground "#e41507"))))
 '(magit-diff-lines-heading           ((t (:background "#d0d0d0" :foreground "#000000"))))
 '(magit-diff-lines-boundary          ((t (:background "#d0d0d0" :foreground "#000000"))))
 '(magit-diffstat-added               ((t (:foreground "#329033"))))
 '(magit-diffstat-removed             ((t (:foreground "#e41507"))))
 '(magit-log-author                   ((t (:foreground "#2E998E"))))
 '(magit-log-date                     ((t (:foreground "#505050"))))
 '(magit-log-graph                    ((t (:foreground "#a0a0a0"))))
 '(magit-process-ok                   ((t (:foreground "#329033" :weight bold))))
 '(magit-process-ng                   ((t (:foreground "#e41507" :weight bold))))
 '(magit-reflog-commit                ((t (:foreground "#329033"))))
 '(magit-reflog-amend                 ((t (:foreground "#9805AE"))))
 '(magit-reflog-merge                 ((t (:foreground "#329033"))))
 '(magit-reflog-checkout              ((t (:foreground "#2981ca"))))
 '(magit-reflog-reset                 ((t (:foreground "#e41507"))))
 '(magit-reflog-rebase                ((t (:foreground "#9805AE"))))
 '(magit-reflog-cherry-pick           ((t (:foreground "#329033"))))
 '(magit-reflog-remote                ((t (:foreground "#2E998E"))))
 '(magit-reflog-other                 ((t (:foreground "#2E998E"))))
 '(magit-bisect-good                  ((t (:foreground "#329033"))))
 '(magit-bisect-skip                  ((t (:foreground "#9E7400"))))
 '(magit-bisect-bad                   ((t (:foreground "#e41507"))))
 '(magit-blame-heading                ((t (:background "#ececec" :foreground "#505050"))))
 '(magit-blame-highlight              ((t (:background "#e8e8e8" :foreground "#000000"))))
 '(magit-blame-name                   ((t (:foreground "#2E998E"))))
 '(magit-blame-date                   ((t (:foreground "#505050"))))
 '(magit-blame-summary                ((t (:foreground "#505050"))))
 '(magit-sequence-pick                ((t (:foreground "#9E7400"))))
 '(magit-sequence-stop                ((t (:foreground "#329033"))))
 '(magit-sequence-part                ((t (:foreground "#9E7400"))))
 '(magit-sequence-head                ((t (:foreground "#2981ca"))))
 '(magit-sequence-drop                ((t (:foreground "#e41507"))))
 '(magit-sequence-done                ((t (:foreground "#505050"))))
 '(magit-sequence-onto                ((t (:foreground "#505050"))))
 '(magit-filename                     ((t (:foreground "#000000"))))
 '(magit-header-line                  ((t (:background "#e8e8e8" :foreground "#000000" :weight bold))))
 '(magit-header-line-log-select       ((t (:background "#e8e8e8" :foreground "#000000" :weight bold))))
 '(magit-mode-line-process            ((t (:foreground "#2981ca" :weight bold))))
 '(magit-mode-line-process-error      ((t (:foreground "#e41507" :weight bold))))

 '(vertico-current                    ((t (:background "#e0e0e0" :extend t))))
 '(vertico-group-title                ((t (:background "#ececec" :foreground "#505050" :weight bold))))
 '(vertico-group-separator            ((t (:background "#ececec" :foreground "#a0a0a0" :strike-through t))))
 '(vertico-multiline                  ((t (:foreground "#505050"))))
 '(vertico-quick1                     ((t (:background "#e8e8e8" :foreground "#2981ca" :weight bold))))
 '(vertico-quick2                     ((t (:background "#e8e8e8" :foreground "#329033" :weight bold))))

 '(orderless-match-face-0             ((t (:foreground "#2981ca" :weight bold))))
 '(orderless-match-face-1             ((t (:foreground "#329033" :weight bold))))
 '(orderless-match-face-2             ((t (:foreground "#9E7400" :weight bold))))
 '(orderless-match-face-3             ((t (:foreground "#9805AE" :weight bold))))

 '(marginalia-documentation           ((t (:foreground "#505050" :slant italic))))
 '(marginalia-key                     ((t (:foreground "#329033"))))
 '(marginalia-type                    ((t (:foreground "#9805AE"))))
 '(marginalia-char                    ((t (:foreground "#2981ca"))))
 '(marginalia-lighter                 ((t (:foreground "#a0a0a0"))))
 '(marginalia-on                      ((t (:foreground "#329033"))))
 '(marginalia-off                     ((t (:foreground "#e41507"))))
 '(marginalia-file-priv-dir           ((t (:foreground "#2981ca"))))
 '(marginalia-file-priv-exec          ((t (:foreground "#329033"))))
 '(marginalia-file-priv-link          ((t (:foreground "#2E998E"))))
 '(marginalia-file-priv-read          ((t (:foreground "#9E7400"))))
 '(marginalia-file-priv-write         ((t (:foreground "#e41507"))))

 '(consult-file                       ((t (:foreground "#000000"))))
 '(consult-bookmark                   ((t (:foreground "#2981ca"))))
 '(consult-async-running              ((t (:foreground "#2981ca"))))
 '(consult-async-finished             ((t (:foreground "#329033"))))
 '(consult-async-failed               ((t (:foreground "#e41507"))))
 '(consult-async-split                ((t (:foreground "#505050"))))
 '(consult-narrow-indicator           ((t (:foreground "#2981ca" :weight bold))))
 '(consult-preview-line               ((t (:background "#ececec"))))
 '(consult-preview-match              ((t (:background "#e0e0e0"))))
 '(consult-preview-cursor             ((t (:background "#d0d0d0"))))

 '(embark-keybinding                  ((t (:foreground "#329033"))))
 '(embark-collect-marked              ((t (:background "#e0e0e0" :foreground "#000000"))))
 '(embark-verbose-indicator-title     ((t (:weight bold))))
 '(embark-selected                    ((t (:background "#ececec"))))
 '(embark-target                      ((t (:foreground "#2981ca" :weight bold))))

 '(ivy-current-match                  ((t (:background "#d0d0d0"))))
 '(ivy-minibuffer-match-face-1        ((t (:background "#e0e0e0"))))
 '(helm-selection                     ((t (:background "#d0d0d0"))))
 '(helm-match                         ((t (:foreground "#2981ca" :weight bold))))
 '(vertico-current                    ((t (:background "#d0d0d0"))))

 '(term-color-black                   ((t (:foreground "#000000" :background "#000000"))))
 '(term-color-red                     ((t (:foreground "#e41507" :background "#e41507"))))
 '(term-color-green                   ((t (:foreground "#329033" :background "#329033"))))
 '(term-color-yellow                  ((t (:foreground "#9E7400" :background "#9E7400"))))
 '(term-color-blue                    ((t (:foreground "#2981ca" :background "#2981ca"))))
 '(term-color-magenta                 ((t (:foreground "#9805AE" :background "#9805AE"))))
 '(term-color-cyan                    ((t (:foreground "#2E998E" :background "#2E998E"))))
 '(term-color-white                   ((t (:foreground "#DDDDDD" :background "#DDDDDD"))))

 '(rainbow-delimiters-depth-1-face    ((t (:foreground "#e41507"))))
 '(rainbow-delimiters-depth-2-face    ((t (:foreground "#2981ca"))))
 '(rainbow-delimiters-depth-3-face    ((t (:foreground "#329033"))))
 '(rainbow-delimiters-depth-4-face    ((t (:foreground "#9E7400"))))
 '(rainbow-delimiters-depth-5-face    ((t (:foreground "#2E998E"))))
 '(rainbow-delimiters-depth-6-face    ((t (:foreground "#9805AE"))))
 '(rainbow-delimiters-depth-7-face    ((t (:foreground "#e41507"))))
 '(rainbow-delimiters-depth-8-face    ((t (:foreground "#505050"))))
 '(rainbow-delimiters-depth-9-face    ((t (:foreground "#a0a0a0"))))

 '(lsp-face-highlight-textual         ((t (:background "#e0e0e0"))))
 '(lsp-face-highlight-read            ((t (:background "#e0e0e0"))))
 '(lsp-face-highlight-write           ((t (:background "#e0e0e0" :underline t))))
 '(lsp-ui-doc-background              ((t (:background "#e8e8e8"))))
 '(lsp-ui-peek-selection              ((t (:background "#d0d0d0"))))
 '(lsp-ui-sideline-code-action        ((t (:foreground "#E6BB00"))))
 '(lsp-face-semhl-operator            ((t (:foreground "#e41507" :weight regular))))
 '(lsp-face-semhl-constant            ((t (:foreground "#1e73be" :weight bold))))
 '(lsp-inlay-hint-face                ((t (:foreground "#606060"))))

 '(which-key-key-face                 ((t (:foreground "#329033"))))
 '(which-key-separator-face           ((t (:foreground "#a0a0a0"))))
 '(which-key-command-description-face ((t (:foreground "#000000"))))
 '(which-key-group-description-face   ((t (:foreground "#000000" :weight bold))))

 '(error                              ((t (:foreground "#e41507" :weight bold))))
 '(warning                            ((t (:foreground "#9E7400" :weight bold))))
 '(success                            ((t (:foreground "#329033" :weight bold)))))

(provide-theme 'pragmata)

;;; pragmata-theme.el ends here
