general {
    lock_cmd = pidof swaylock || swaylock -f --screenshots --effect-blur 7x5 --effect-vignette 0.5:0.5 --clock --indicator --indicator-radius 120 --indicator-thickness 10 --ring-color 4f5459 --ring-ver-color 3584e4 --ring-wrong-color bf616a --key-hl-color 3584e4 --text-color ffffff --inside-color 00000088
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 900
    on-timeout = loginctl lock-session
}

listener {
    timeout = 900
    on-timeout = wlopm --off \*
    on-resume = wlopm --on \*
}
