border.width: 1
window.titlebar.padding.width: 8
window.titlebar.padding.height: 8

window.button.width: 24
window.button.height: 24
window.button.spacing: 6
window.button.hover.bg.corner-radius: 12
window.button.hover.bg.color: #0000001f
window.label.text.justify: Center

window.active.border.color: #c0bfbc
window.active.title.bg: Solid
window.active.title.bg.color: #deddda
window.active.label.text.color: #1d1d1d
window.active.button.unpressed.image.color: #5d5d5d
window.active.shadow.size: 30
window.active.shadow.color: #00000040

window.inactive.border.color: #d3d2d0
window.inactive.title.bg: Solid
window.inactive.title.bg.color: #f0efed
window.inactive.label.text.color: #7a7a7a
window.inactive.button.unpressed.image.color: #9a9a9a
window.inactive.shadow.size: 16
window.inactive.shadow.color: #00000026

menu.border.color: #c0bfbc
menu.border.width: 1
menu.items.bg.color: #f6f5f4
menu.items.text.color: #1d1d1d
menu.items.active.bg.color: #3584e4
menu.items.active.text.color: #ffffff
menu.title.bg.color: #deddda
menu.title.text.color: #1d1d1d

osd.bg.color: #1d1d1d
osd.border.color: #0d0d0d
osd.border.width: 1
osd.label.text.color: #ffffff
