border.width: 1
padding.width: 6
padding.height: 4

window.active.border.color: #1e1e1e
window.active.title.bg.color: #363636
window.active.title.bg.type: Solid
window.active.label.text.color: #ffffff
window.active.button.unpressed.bg.color: #363636
window.active.button.unpressed.bg.type: Solid
window.active.button.unpressed.image.color: #d4d4d4
window.active.button.pressed.bg.color: #2b2b2b
window.active.button.pressed.bg.type: Solid
window.active.button.pressed.image.color: #ffffff
window.active.button.hover.bg.color: #464646
window.active.button.hover.bg.type: Solid
window.active.button.hover.image.color: #ffffff
window.active.handle.bg.color: #363636
window.active.handle.bg.type: Solid
window.active.grip.bg.color: #1e1e1e
window.active.grip.bg.type: Solid

window.inactive.border.color: #2a2a2a
window.inactive.title.bg.color: #2b2b2b
window.inactive.title.bg.type: Solid
window.inactive.label.text.color: #6c6c6c
window.inactive.button.unpressed.bg.color: #2b2b2b
window.inactive.button.unpressed.bg.type: Solid
window.inactive.button.unpressed.image.color: #6c6c6c
window.inactive.button.hover.bg.color: #363636
window.inactive.button.hover.bg.type: Solid
window.inactive.button.hover.image.color: #6c6c6c
window.inactive.handle.bg.color: #2b2b2b
window.inactive.handle.bg.type: Solid
window.inactive.grip.bg.color: #2a2a2a
window.inactive.grip.bg.type: Solid

menu.bg.color: #303030
menu.bg.type: Solid
menu.border.color: #1a1a1a
menu.border.width: 1
menu.items.bg.color: #303030
menu.items.bg.type: Solid
menu.items.text.color: #e5e5e5
menu.items.disabled.text.color: #6c6c6c
menu.items.active.bg.color: #3584e4
menu.items.active.bg.type: Solid
menu.items.active.text.color: #ffffff
menu.title.bg.color: #3d3d3d
menu.title.bg.type: Solid
menu.title.text.color: #ffffff

osd.bg.color: #1d1d1d
osd.bg.type: Solid
osd.border.color: #0d0d0d
osd.border.width: 1
osd.label.text.color: #ffffff
