border.width: 1
window.titlebar.padding.width: 8
window.titlebar.padding.height: 8

window.button.width: 24
window.button.height: 24
window.button.spacing: 6
window.button.hover.bg.corner-radius: 12
window.button.hover.bg.color: #ffffff26
window.label.text.justify: Center

window.active.border.color: #1e1e1e
window.active.title.bg: Solid
window.active.title.bg.color: #363636
window.active.label.text.color: #ffffff
window.active.button.unpressed.image.color: #d4d4d4
window.active.shadow.size: 30
window.active.shadow.color: #00000070

window.inactive.border.color: #2a2a2a
window.inactive.title.bg: Solid
window.inactive.title.bg.color: #2b2b2b
window.inactive.label.text.color: #6c6c6c
window.inactive.button.unpressed.image.color: #6c6c6c
window.inactive.shadow.size: 16
window.inactive.shadow.color: #00000050

menu.border.color: #1a1a1a
menu.border.width: 1
menu.items.bg.color: #303030
menu.items.text.color: #e5e5e5
menu.items.active.bg.color: #3584e4
menu.items.active.text.color: #ffffff
menu.title.bg.color: #3d3d3d
menu.title.text.color: #ffffff

osd.bg.color: #1d1d1d
osd.border.color: #0d0d0d
osd.border.width: 1
osd.label.text.color: #ffffff
