[font]
size = 13
builtin_box_drawing = true

[font.normal]
family = "Berkeley Mono"
style = "Book SemiCondensed"

[font.bold]
family = "Berkeley Mono"
style = "Bold SemiCondensed"

[font.italic]
family = "Berkeley Mono"
style = "Book SemiCondensed Oblique"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold SemiCondensed Oblique"

[font.offset]
x = 0
y = 4

[font.glyph_offset]
x = 0
y = 2

[window]
dynamic_padding = false
decorations = "none"
opacity = 1.0

[window.dimensions]
columns = 150
lines = 65

[window.padding]
x = 10
y = 10

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
semantic_escape_chars = ",?`|:\"' ()[]{}<>"
save_to_clipboard = true

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "Never"

[colors.primary]
background = "#000000"
foreground = "#D8DEE9"

[colors.normal]
black = "#2A2A2A"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EFB080"
blue = "#85C1FC"
magenta = "#AA9BF5"
cyan = "#88C0D0"
white = "#D8DEE9"

[colors.bright]
black = "#505050"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBC88D"
blue = "#85C1FC"
magenta = "#C582BF"
cyan = "#83D6C5"
white = "#D8DEE9"

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"
