[terminal.shell]
program = "tmux"
args = ["new-session"]

[window]
padding = { x = 12, y = 12 }

[font]
normal = { family = "Berkeley Mono", style = "SemiCondensed" }
bold = { family = "Berkeley Mono", style = "Bold SemiCondensed" }
italic = { family = "Berkeley Mono", style = "SemiCondensed Oblique" }
bold_italic = { family = "Berkeley Mono", style = "Bold SemiCondensed Oblique" }
size = 12.0

[colors.primary]
background = "#111313"
foreground = "#c2c9c9"
dim_foreground = "#858f8f"

[colors.cursor]
text = "#111313"
cursor = "#dfe5e5"

[colors.selection]
text = "CellForeground"
background = "#0f2f2d"

[colors.search.matches]
foreground = "#f2f6f6"
background = "#0f2f2d"

[colors.search.focused_match]
foreground = "#111313"
background = "#01a59e"

[colors.normal]
black = "#181b1b"
red = "#d47a72"
green = "#8dbab7"
yellow = "#cfb57c"
blue = "#01a59e"
magenta = "#dfe5e5"
cyan = "#8dbab7"
white = "#c2c9c9"

[colors.dim]
black = "#111313"
red = "#d47a72"
green = "#8dbab7"
yellow = "#cfb57c"
blue = "#01a59e"
magenta = "#858f8f"
cyan = "#8dbab7"
white = "#858f8f"

[colors.bright]
black = "#5a6464"
red = "#d47a72"
green = "#8dbab7"
yellow = "#cfb57c"
blue = "#01a59e"
magenta = "#dfe5e5"
cyan = "#8dbab7"
white = "#f2f6f6"
